### ISSUE TITLE
Mismatched library names between Windows and *nices

### ISSUE THREAD

**Issue by bit2shift** [nigels-com/glew#102]
On Windows, GLEW's static library is named `libglew32.a`, while on Ubuntu I'm getting `libGLEW.a`.
I'm trying to avoid OS detection like the plague on a project of mine, but this hinders my progress.

**Comment by nigels-com** [comment]
Agreed, the Windows naming scheme is unfortunate.  But it's aligned with `opengl32.dll` so I don't forsee changing it.

**Comment by bit2shift** [comment]
Only system DLLs follow that convention and, even now on x64 systems, it's deprecated.
There's absolutely no rational reason to have different base names for libraries these days.
Look at GLFW: `glfw3.dll`/`libglfw.so` (I'll have to talk about that with them)

Is it too much asking for uniformity between platforms?

**Comment by nigels-com** [comment]
GLEW is widely used and has long maintained ABI compatibility.  I'd fully expect old windows binaries to work fine with a new `glew32.dll` (no recompile/relink required).  So no, I consider it entrenched for a 15-year-old library like GLEW.

**Comment by bit2shift** [comment]
Then we need an option to specify the name, because
<details>fuck OS detection routines.</details>

**Comment by nigels-com** [comment]
Yeah, cross-platform is a pain.  If you're on Linux you ought to have no drama forking GLEW and messing with the Windows build, or the cmake stuff.

**Comment by nigels-com** [comment]
Probably also worth mentioning that glew.c is trivial to statically link to a project, by design.

**Comment by bit2shift** [comment]
The problem with statically linking with something is being subjected to that something's dependencies.
If only static libs were capable of including other static libs. Maybe they can and I don't know.

**Comment by bit2shift** [comment]
Oh, wait, I could parse the pkg-config files that both GLEW and GLFW generate to extract the values of both `Libs` and `Libs.private` minus `-L${libdir}`.
And definitely sort all `Libs` before `Libs.private`.
