### ISSUE TITLE
X11/EGL: Segfault if glXGetCurrentDisplay() returns NULL

### ISSUE THREAD

**Issue by vladtcvs** [nigels-com/glew#103]
I have segfault in glxewInit() at 
glXQueryVersion(glXGetCurrentDisplay(), &major, &minor);

because glXQueryVersion uses XInitExtension(), which segfaults when display == NULL

glew 2.0.0
mesa both 11.1 and git 98f734e758ee6a7ea0d9b86a0416d0418d2e7fc5
libX11 1.6.3

I don't sure, that it is a bug of glew, may be it should be fixed in libX11

**Comment by vladtcvs** [comment]
Problems appears with qt-opengl (4.8.6), when it uses egl.

**Comment by nigels-com** [comment]
Ah, I see.  Yes it makes sense to deal with this more gracefully when `display==NULL`.

Thanks for the report.

**Comment by nigels-com** [comment]
GLEW needs to be built with -DGLEW_EGL to be used with egl, rather than GLX.  I'm adding some code to exit a little more gracefully in the case of `glXGetCurrentDisplay() == NULL`

**Comment by nigels-com** [comment]
This is fixed in master branch, will appear in next release.
