### ISSUE TITLE
Can't open extensions/gl/GL_ARB_vertex_shader: No such file or directory.

### ISSUE THREAD

**Issue by lamogui** [nigels-com/glew#110]
Hello
Tanks for your great lib wonderful work !
if I may i encounter multiple errors when trying to compile auto with command "make" or the whole project with "make extentions" (current repo version or at tag 1.13).

log:

```
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 353.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 357.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 353.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 357.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 353.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 357.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 353.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 357.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 353.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 357.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 353.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 357.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 353.
Hexadecimal number > 0xffffffff non-portable at bin/parse_spec.pl line 357.
bin/filter_gl_ext.sh     extensions/gl
Can't do inplace edit on extensions/gl/GL_HP_occlusion_test: No such file or directory.
Can't open extensions/gl/GL_HP_occlusion_test: No such file or directory.
Can't do inplace edit on extensions/gl/GL_ARB_vertex_shader: No such file or directory.
Can't open extensions/gl/GL_ARB_vertex_shader: No such file or directory.
Can't open extensions/gl/GL_ARB_vertex_shader: No such file or directory.
Can't open extensions/gl/GL_ARB_vertex_shader: No such file or directory.
grep: extensions/gl/GL_ARB_vertex_shader: No such file or directory
make[1]: *** [extensions/gl/.dummy] Error 2
make[1]: Leaving directory `/mnt/c/Repository/glew/auto' 
```

Thanks in advance for this

**Comment by nigels-com** [comment]
If your aim is to _use_ GLEW, I'd recommend building one of the releases, rather than regenerating the code:  [2.0.0](https://sourceforge.net/projects/glew/files/glew/2.0.0/) or [1.13.0](https://sourceforge.net/projects/glew/files/glew/1.13.0/)

If your aim is to extend or maintain GLEW, Linux or Mac is ideal for having the necessary tools at hand to generate the source code.

**Comment by lamogui** [comment]
@nigels-com my aim is to maintain and patch glew 1.13 to be core profile 3.3 compatible (by removing getString and replace it by getStringi), since the 2.0 as removed glewmx. I use the new linux toolchain of windows 10. I already patched the generated code but I wanted to patch the 1.13 generator directly to pull request it here. It consume a lot of time to maintain a patch that is only applicable after the generation.

**Comment by nigels-com** [comment]
Ah, that's a worthy project.  I would request in that case that GLEW 1.13 tracks GLEW 2.0.0 as closely as reasonably possible.  There does seem like interest in continuing with MX, and therefore I have two branches to maintain now, instead of one.

I don't have Windows 10 at hand to try the code generation on.  If you have too much trouble I'd suggest a virtual box running perl etc natively.

**Comment by nigels-com** [comment]
Any further on this issue?  I'm closing ones that don't seem directly actionable.

**Comment by lamogui** [comment]
I manually patched the code after the generation so for me I won't follow more this issue. I don't know if anybody got the same issue to generate the code. 
I didn't retried since.
If anybody want to use the patch it is available here https://github.com/Qlex42/docgl/blob/master/extern/src/GL/glew.c 
I also reference this issue because there is a mix between the issues https://github.com/nigels-com/glew/issues/38

Let's close this one until somebody didn't give up like me and tried to generate the code with this error.
