### ISSUE TITLE
src\glew.c and other files don't exist

### ISSUE THREAD

**Issue by zwcloud** [nigels-com/glew#111]
The Visual Studio 2013 projects (vc12) are broken.  Using glew-2.0.0.

![Imgur](http://i.imgur.com/s9tSgfy.png)

> c1 : fatal error C1083: Cannot open source file: '..\..\src\glew.c': No such file or directory

**Comment by zwcloud** [comment]
I didn't notice the code generation section, sorry.

**Comment by nigels-com** [comment]
No problem.  It seems quite the thing nowadays to build directly from the git repo.
