### ISSUE TITLE
cmake-testbuild.sh fails on macOS Sierra

### ISSUE THREAD

**Issue by karamellpelle** [nigels-com/glew#116]
The build script `cmake-testbuild.sh` fails. It can not find files `src/glewinfo.c` and `include/GL/wglew.h`. Also it can not detect linker language; see attached file [build.txt](https://github.com/nigels-com/glew/files/569617/build.txt).

I have cmake version 3.6.2 and newest XCode.

**Comment by nigels-com** [comment]
I'd suggesting building from the release tgz, rather than the bare git repository.

https://sourceforge.net/projects/glew/files/glew/2.0.0/glew-2.0.0.tgz/download

**Comment by karamellpelle** [comment]
OK, I found the release commit hash, so I can add it as a submodule to my project too. Thanks! 🏅
