### ISSUE TITLE
Linker language cannot be determined on Linux

### ISSUE THREAD

**Issue by karamellpelle** [nigels-com/glew#124]
Before I added glew as a submodule to my project, I wanted to make sure it build. It did not. I did the following (from the glew root):

    $ mkdir mybuild
    $ cd mybuild
    $ cmake ../build/cmake

It gave [this error](https://github.com/nigels-com/glew/files/661931/glew_error.txt): _Linker language cannot be determined_.

**Comment by nigels-com** [comment]
See: https://github.com/nigels-com/glew/issues/85

In a nutshell it's recommended to use a release snap-shot rather than git submodule.
