### ISSUE TITLE
Opengl.org SDK changes and GLEW

### ISSUE THREAD

**Issue by oddhack** [nigels-com/glew#132]
We're going to be restructuring the SDK area of www.opengl.org and, since GLEW is listed there, wanted to let you know and ask what the current state of the project is and if it should continue to be listed (it looks pretty active, but this is a boilerplate request to all the project owners.

Jon Leech
Khronos

**Comment by nigels-com** [comment]
Hi Jon,

GLEW is still being maintained, and seems as popular as ever, judging by downloads.  The "thread-safe support for multiple rendering contexts" aspect (GLEW MX) was dropped in version 2.0 to reduce implementation complexity.  There is some discussion of how to support that, but no concrete action.  GLEW does not support both core and compatibility contexts, which was one pain point for quite some time.

-- Nigel
