### ISSUE TITLE
Using glew with OSMesa

### ISSUE THREAD

**Issue by jjmcwill** [nigels-com/glew#135]
How does the OSMesa support work with glew and Linux? 

If I want to link only against libOSMesa.so, libGLEW.so seems to have unmet dependencies that are only in libGL:

glXGetClientString(), glXGetProcAddressARB(), and glXQueryVersion()

**Comment by nigels-com** [comment]
Try building with GLEW_OSMESA defined.

```
$ cat config/Makefile.linux-osmesa
include config/Makefile.linux

LDFLAGS.GL = -lOSMesa
CFLAGS.EXTRA += -DGLEW_OSMESA
$ make SYSTEM=linux-osmesa
...
```

**Comment by nigels-com** [comment]
Anything further on this?
