### ISSUE TITLE
Library names change if compiled with CMake

### ISSUE THREAD

**Issue by claudiofantacci** [nigels-com/glew#141]
Hi everyone 😄 

I noticed that compiling `glew` with `CMake` the name of the generated libs differs from the ones generated with `make`.
You can see the differences in [this comment](https://github.com/Homebrew/homebrew-core/pull/12722#pullrequestreview-33980701) of a PR I opened on the [homebrew-core](https://github.com/Homebrew/homebrew-core) project.

I this is a desired behaviour or not?
Thanks!

**Comment by nigels-com** [comment]
In my opinion that's a bug.  The `cmake` build ought to match the `make` build as closely as possible.

**Comment by claudiofantacci** [comment]
Ok, that's reasonable.

I can try to look into this during the next weeks and eventually issuing a PR.

**Comment by nigels-com** [comment]
For what's it's worth I still consider `make` the primary build.  What's the motivation for going the cmake road?  (Such overkill for one C compilation unit!)

**Comment by claudiofantacci** [comment]
As far as my opinion is concerned, I (and the place where I work in) make extensive use of CMake facilities to deal with very big C/C++ projects (you can have a look at [robotology](https://github.com/robotology) and [YARP](https://github.com/robotology/yarp) in particular) for managing their build process with compiler-independent method, which is modular and makes packages integration easy and (quite) straightforward.

I'm using `glew` for OpenGL-based AR applications, and I found out that the only way to get the `glew` cmake config files from the project was indeed to build it with CMake, which was not supported by `brew`. As a consequence, I wanted to make a contribution with [this PR](https://github.com/Homebrew/homebrew-core/pull/12722#pullrequestreview-33980701).

**Comment by nigels-com** [comment]
Indeed.  Part of my day job is maintaining large C++ builds, mostly using cmake.  When it works it great, but when it breaks I think it's miserable, to be honest.

**Comment by nigels-com** [comment]
But, of course, each to their own.  If it's valuable to you or Homebrew land in general, then fine!

**Comment by claudiofantacci** [comment]
When it breaks.
![I'm out!](https://media.giphy.com/media/cm1xDStzn4JFK/giphy.gif)

**Comment by claudiofantacci** [comment]
> But, of course, each to their own. If it's valuable to you or Homebrew land in general, then fine!

Thanks!
