### ISSUE TITLE
Mac/Homebrew: Does glew require GLU?

### ISSUE THREAD

**Issue by claudiofantacci** [nigels-com/glew#142]
While trying to address [this issue](https://github.com/nigels-com/glew/issues/141) I was told of another (apparent) issue relating to `glew.pc`: it reports `Requires: glu` while it seems that `glew` does not depend on it.

A rather old discussion about it can be found [here](https://github.com/Homebrew/legacy-homebrew/issues/22025) and a workaround was made available on macOS using `brew` package manager as reported [here](https://github.com/Homebrew/legacy-homebrew/issues/22025#issuecomment-23732918) (which basically deletes the `Requires: glu` in `glew.pc`).

Is GLU a real mandatory dependency (which does not seem to be the case) or is it a problem related to `glew.pc` file?

Thanks!

**Comment by nigels-com** [comment]
In a general sense, yes.  `glew.h` does include the GLU header.  And `visualinfo` needs to link GLU.

However, apps that link GLEW don't need GLU via GLEW at runtime.

It's a bit unfortunate that `glew.h` drags in GLU, but it's been that way for a long time.

**Comment by nigels-com** [comment]
I pushed some changes just now to conditionally put `Requires: glu` in `glew.pc` in `GLEW_APPLE_GLX=1` mode only for Mac.  (makefile build)

For cmake I've made a similar change to prevent `Requires: glu` in `glew.pc` for Mac builds, also.

Hopefully that resolves the need for downstream handling.

**Comment by claudiofantacci** [comment]
Perfect! Thanks! 🎉
