### ISSUE TITLE
Ubuntu16.04/Nvidia: SIGSEVG when calling glXGetCurrentDisplay

### ISSUE THREAD

**Issue by astepanov83** [nigels-com/glew#144]
Hello!

I'm trying to compile and run glewinfo utility. Actually, I use a fork of this repo with another CMakeLists.txt, but the code is in sync with this repository. I'm able to compile everything fine, but when I run glewinfo I get SIGSEGV. I tried to find out the reason and here's what I found. In `glxewInit` function I see the following piece of code:

```
  /* check for a display */
  display = glXGetCurrentDisplay();
  if (display == NULL) return GLEW_ERROR_NO_GLX_DISPLAY;
  /* initialize core GLX 1.2 */
  if (_glewInit_GLX_VERSION_1_2()) return GLEW_ERROR_GLX_VERSION_11_ONLY;
```

`glXGetCurrentDisplay` is called before being initialized in `_glewInit_GLX_VERSION_1_2`. So the call is made at the address 0x0. Then I swap these calls and voila, everything works!

Am I missing something? I can try to compile exactly this repo and not to use build files in forked repos. Unfortunately I ran into some problems while building it. But it looks like my problem has nothing in common with how I compile GLEW.

Best regards,
Alex

**Comment by nigels-com** [comment]
I'll check on Linux.  That did change recently, as I recall.

My main suggestion is to use the GLEW 2.0.0 release tarball.  Everything else is "release candidate".

**Comment by nigels-com** [comment]
Oops!  Yes, broken.  Now fixed.

Thanks for the report.
