### ISSUE TITLE
VS BUILD BROKEN:  Cannot open source file: '..\..\src\glew.c': No such file or directory	

### ISSUE THREAD

**Issue by mDanz** [nigels-com/glew#145]
I'm trying to build glew using Visual Studio 14. But it seems that the core files needed for glew are missing: glew.c, glewinfo.c and glew.h. Am I missing something?

Best regards,
mDanz

**Comment by miguelinux** [comment]
AFAIK you should use the [zip source file](https://sourceforge.net/projects/glew/files/glew/2.0.0/glew-2.0.0.zip/download) provided in the webpage.

If you like to use the github repo you should build the glew files from the auto directory. I've read this in the [README](https://github.com/nigels-com/glew#build) file.

**Comment by nigels-com** [comment]
Especially for Windows, the general advice is to build GLEW from one of the official releases, rather than from scratch.  See: [GLEW homepage](http://glew.sourceforge.net/)
