### ISSUE TITLE
Getting "No rule to make target 'src/glew.c'" when trying to build with MinGW

### ISSUE THREAD

**Issue by birgersp** [nigels-com/glew#147]
Hi,

I'm trying to build the project on Windows 10 using MinGW. Running `mingw32-make.exe` in the project root directory yields the following error:

>mingw32-make: *** No rule to make target 'src/glew.c', needed by 'tmp/mingw/default/shared/glew.o'. 
 Stop.

**Comment by birgersp** [comment]
According to [this forum post](http://www.cplusplus.com/forum/unices/149883/), I need to run `mingw32-make extensions` first. This fixed this problem.

But maybe the build instructions should reflect this? Or did I mess up somewhere?

**Comment by nigels-com** [comment]
On windows the general advice is to build from the release archive, rather than git repository.

**Comment by yasamoka** [comment]
Could this perhaps be included on the homepage README, under Windows MSYS2 build instructions? That would be great.
