### ISSUE TITLE
Packaging glew with conan

### ISSUE THREAD

**Issue by dimi309** [nigels-com/glew#150]
Hello,

I've been using glew for a while. Recently, I have packaged it with conan, an open source C/C++ package manager and placed the package on bintray:

https://bintray.com/dimi309/conan-packages/glew%3Adimi309

I hope you don't mind :)

The package is in the process of being evaluated for inclusion into a curated repository on bintray, which is to only contain good quality conan packages. I am writing to ask you if you would be interested in maintaining this package directly. I can provide you with the packaging code (actually, you can just copy it, since it's open source) or even introduce a pull request with some non-intrusive changes that would allow you to package it directly from the main glew repository.

**Comment by nigels-com** [comment]
Conan looks interesting.  I'd certainly give a pull request serious consideration.  I'm curious about how good a job it does to ignore the system/toolchain libraries (such as zlib) and enforces the specified (possibly pinned) versions.

I did get some warnings on Mac with the GLEW _conanfile.py_

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CONAN_COMPILER
    CONAN_COMPILER_VERSION
    CONAN_EXPORTED
    CONAN_LIBCXX
```

**Comment by dimi309** [comment]
Many thanks for your reply!

I have now been working with conan for about a year (note that I am not affiliated with conan or bintray in any way) and I can say that you can definitely avoid system and toolchain libraries, but only if you choose to. For example, when I build my own project with conan on Debian, I am certain to be using the conan-packaged versions of glew and glfw. I also specify which version or version range I want. However, when deploying the glfw package, I tell it to look for mesa dev among the operating system's apt deployed packages and not on bintray.

About the warning, these variables are provided by the conan generator to CMake, but I did not need them for the build. To my knowledge (and I will admit here that I am not a conan super-expert), it is not a problem that they show up in this manner.

It might be a good idea that I introduce a conservative pull request with the conan packaging configuration (completely non-intrusive to the rest of the project) so that you can see what things might look like. Of course there is no problem on my side if you choose to reject it. If you think it's ok, then, you can let me know if you would like to take over the package on bintray (I will stop the approval process of my own package in that case), or let me take care of the automated builds, packaging and support of this particular aspect. In the latter case, I think it would still be a plus for the sake of coherence that the packaging code is stored with the rest of the glew code-base, rather than in a separate repository as is happening now.

Once again, thank you for taking the time to look into this.

**Comment by dimi309** [comment]
I've introduced the pull request:

https://github.com/nigels-com/glew/pull/151

**Comment by dimi309** [comment]
As discussed (see https://github.com/nigels-com/glew/pull/187), the glew conan package is now maintained by the bincrafters team.
