### ISSUE TITLE
No sources in src/

### ISSUE THREAD

**Issue by shybovycha** [nigels-com/glew#159]
I was trying to build glew with both CMake and Make (used source from `master` branch) and both of them failed saying

```
Cannot find source file:

    /Users/ashubovych/projects/cpp/3d_engine/vendor/glew/include/GL/wglew.h
```

And this is correct - I can't see any sources in the repo (again, on `master` branch).

What's going on?

**Comment by nigels-com** [comment]
Ordinarily it's recommended to use the current release, rather than git master branch.

**Comment by shybovycha** [comment]
You mean ZIP/TGZ archive?

That wouldn't work in my case - I wanted to use glew as a git submodule.

**Comment by nigels-com** [comment]
Ah, I see.

**Comment by nigels-com** [comment]
There is some discussion of this over at #13 

To summarise, the GLEW repo is for version controlling the make/perl/build scripts, but not the generated C source code.  The general idea is that there could be a seperate git repo that tracks the release tgz/zip for submodule purposes.  But that work has not been undertaken yet.

**Comment by nigels-com** [comment]
I do have some reluctance as a maintainer, that unreleased (and untested) master-branch versions of GLEW should not be used in production.  It's this consideration that motivates a seperate repository tracking the releases.

**Comment by wiranoid** [comment]
Seperate repository with releases would be great

**Comment by fgfuchs** [comment]
I would suggest to do what is more common, and change the philosophy of "master" @nigels-com . Why not use feature branches for development. When they become stable they can be pulled into master as a new release version? In that way, master is always the latest release. Having a master that cannot be built seems kind of a funny strategy to me.
(Another way would be to have a default branch that is the latest release.)
