### ISSUE TITLE
-DNDEBUG causes segmentation fault 

### ISSUE THREAD

**Issue by arekmd** [nigels-com/glew#163]
I'm using CMake, GLEW on Ubuntu 14.04. 

My program runs fine when compiled as "Debug", but compiled as "Release" first OpenGL function call causes SEGFAULT.

After some digging, I found that NDEBUG is troublemaker. CMake "Release" build adds -DNDEBUG compiler parameter. 

NDEBUG deactivates assert(..) function. 

I'm not sure, that it's a bug.

**Comment by nigels-com** [comment]
Could you attach a stack trace?  Try running with `gdb --args` and when it crashes type `where` at the gdb prompt.

Most likely GLEW isn't initialised or an extension is being used that isn't available.

-- Nigel

**Comment by arekmd** [comment]
That's my fault.

I missed that line:
```CPP
assert(glewInit() == GLEW_OK);
```

Sorry for wasting your time.
