### ISSUE TITLE
E: Unable to locate package libXmu-dev

### ISSUE THREAD

**Issue by Kprezeorsky** [nigels-com/glew#165]
errors upon downloading and installing pacakges for glew.  See below... please advise.
--------------------------------------------------------------------------
kap@LINUX:~$ sudo apt-get install libXmu-dev libXi-dev libgl-dev dos2unix git wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libgl1-mesa-dev' instead of 'libgl-dev'
E: Unable to locate package libXmu-dev
E: Unable to locate package libXi-dev

**Comment by nigels-com** [comment]
Sounds like things have changed recerntly in Debian and/or Ubuntu.  Most of my machines are are on Ubuntu Xenial 16.04.  But, best to be ready for 18.04...

**Comment by nigels-com** [comment]
Works for me on Ubuntu 17.10
