### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by blitz-research** [nigels-com/glew#166]
Hi,

I'm just curious why GL framebuffers aren't implemented in glew as part of opengl 3.0? This is apparently when framebuffers were added to the gl spec.

Glew instead appears to consider framebuffers to still be an extension,  ie: GL_ARB_framebuffer_object 

Not a huge deal, the API is working, but I'm writing a convertor to implement GL in another language and found this a bit odd and wonder if there's more oddness to come!

Bye,
Mark

**Comment by nigels-com** [comment]
GLEW is extension-centric, rather than version-centric.  There would have been a time when a lot of OpenGL 3.0 functionality was available via extensions, even for GPU/driver not fully OpenGL 3.0 compatible.

**Comment by blitz-research** [comment]
Thanks for the reply.

I guess it's pointless to ask 'is there a header file for opengl3.0'
anywhere?

Can I safely assume 3.0 contains the entire glDrawBuffers extension then?

If not, is there anywhere I can find out what is and what is not definitely
supported by opengl3.0?

**Comment by nigels-com** [comment]
The various OpenGL specs will say which extensions have been incorporated.
Such as: [glspec30.pdf Appendix N](https://www.khronos.org/registry/OpenGL/specs/gl/glspec30.pdf)

I think it's more common to check for extension support than the complexity of checking for an extension _or_ the appropriate OpenGL version.
