### ISSUE TITLE
GLEW version

### ISSUE THREAD

**Issue by HelliceSaouli** [nigels-com/glew#168]
Hi so i have ubuntu with glew 1.1.0  and i'm trying to update glew version because i need it.  installed the latest version yet when i run the program and check for glew version glewGetString(GLEW_VERSION) i get version 1.1.0. any solution I tried editing the glew.pc file yet the same problem

**Comment by nigels-com** [comment]
What version of Ubuntu is it?  Likely the problem is installing GLEW in a manner that overrides the system-installed one.  But usually the easier solution is to statically complile the *glew.c* directly into the application.

**Comment by HelliceSaouli** [comment]
Oh thanks for the reply. well the problem was me using eclipse Night  IDE which comes with Cuda and it's own set of OpenGL and Glew files. i manually searched for all Glew files in system removed them re-install the new version and now it is working fine
