### ISSUE TITLE
glew cmake project requires a c++ compiler

### ISSUE THREAD

**Issue by suikki** [nigels-com/glew#169]
cmake projects enable both C and C++ as project languages by default.

I have a pure C project that fails to compile when I include glew like this:

    add_subdirectory("external/glew-2.1.0/build/cmake" EXCLUDE_FROM_ALL)

This could be fixed in the glew CMakeLists.txt by using:

    project (glew C)

instead of:

    project (glew)

**Comment by nigels-com** [comment]
I see.

Going by the [cmake documentation for project](https://cmake.org/cmake/help/v3.0/command/project.html) I'd be happy to merge such a change.
