### ISSUE TITLE
Calling convention differs between x64 & Win32 builds

### ISSUE THREAD

**Issue by msc-** [nigels-com/glew#173]
Win32 builds use __stdcall calling convention while x64 builds use __cdecl. This is because of what looks like a bug. The calling convention setting in glew.h is bracketed by #ifdef _WIN32, which is only defined when building for the Win32 platform. At least that's how it is in an old glew.h that I have. The latest 2.1.0 binaries still have the issue so the problem must still be in the latest generated glew.h.

This is a problem when searching a loaded dll for e.g. glewInit because with __stdcall this becomes glewInit@0. So users need to ifdef their code to find the symbol in 32-bit or 64-bit versions.

I'm guessing this is inadvertent.

**Comment by msc-** [comment]
My diagnosis of why the conventions differ seem to be incorrect.  _WIN32 is defined when building for x64 as well in another project I am working on and the project isn't setting it.

**Comment by nigels-com** [comment]
Are these the cmake-built binaries, or the bundled Visual Studio projects?

**Comment by msc-** [comment]
The ones downloaded from https://sourceforge.net/projects/glew/files/glew/2.1.0/glew-2.1.0-win32.zip/download.

I also saw the problem in version 1.13 built with one of the bundled VS projects. I couldn't get that one to build with cmake.

**Comment by nigels-com** [comment]
According to [Microsoft Documentation](https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names) the C functions should not be decorated in a 64-bit environment.  So the problem concerns manual loading in 32-bit mode?

**Comment by msc-** [comment]
Ahh! Yes then the problem is manual loading in 32-bit mode. Ideally that should use __cdecl as well so the names are not decorated.

**Comment by nigels-com** [comment]
As far as I recall, __stdcall is the Win32 convention and GLEW is using that to align with opengl32.dll.  I think the entry points can be forced with a (generated) .def file, but there would still be a reluctance to breaking with the GLEW ABI for 32-bit Windows.  Is it just a handfull of entry points, or all of GLEW you're aiming to load?

**Comment by msc-** [comment]
Yes, I think __stdcall is the default. I'm loading just 2 entry points: `glewInit` and `glewGetErrorString` using SDL_LoadFunction which doesn't handle name decoration. I've added #ifdefs to my code for now.

**Comment by nigels-com** [comment]
Anything further on this?  Time to close the issue?

**Comment by msc-** [comment]
From your earlier comments, I assumed you weren't going to change it. I added #ifdefs to my code, as mentioned, to pass the decorated name when compiled for Windows x86. Ugly but functional. I will welcome any alternative suggestions. I'll close this.
