### ISSUE TITLE
Issue while installing GLEW

### ISSUE THREAD

**Issue by samarth1211** [nigels-com/glew#176]
Hi,

I am new to Linux. And I might me making a mistake in the process. 
My deepest apologies in advance.
The only reason I am asking is because i am stuck.

I am getting following issue while installing:
samarth@samarth-170X:~/Downloads/glew/build/cmake$ sudo make install
Scanning dependencies of target glew
[ 12%] Building C object CMakeFiles/glew.dir/home/samarth/Downloads/glew/src/glew.c.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'lib/libGLEW.so.2.1.0'.  Stop.
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/glew.dir/all' failed
make[1]: *** [CMakeFiles/glew.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Below is the screen shot for the process i am following:
![image](https://user-images.githubusercontent.com/30208254/36077915-6d0fe2ca-0f96-11e8-97be-669e5c3ef1f4.png)

**Comment by nigels-com** [comment]
Does this help?

`$ sudo apt-get install libgl-dev libosmesa-dev`

**Comment by samarth1211** [comment]
Yes 👍 , for time being Installation of mentioned libraries has solved the problem.
Thank you very much.

Looks like all my projects must be re-compiled. :(

I am still wondering on what went wrong in the installation. 
Because I have been using GLEW since last six months, and i did not face any installation issues then.

I will trying again for installing version 2.1.0 .
I hope to not to make the same mistake again.

**Comment by nigels-com** [comment]
Anything further on this?  Can we close the issue?

**Comment by samarth1211** [comment]
Hi,

I'm sorry for not closing it.

Yes, the issue is solved and I was able to install the current version of
glew.

Thank you so much for your assistance.

Regards,
Samarth
