### ISSUE TITLE
glew-1.13.tar.gz missing files

### ISSUE THREAD

**Issue by bartoszek** [nigels-com/glew#179]
There is a problem with archived glew package version 1.13.0. Some files are missing, which prevents completing build process.
`diff -qr sourceforge-glew-1.13.0/ github-glew-glew-1.13.0/`
```
Only in sourceforge-glew-1.13.0/auto: extensions
Only in sourceforge-glew-1.13.0/build: glew.rc
Only in sourceforge-glew-1.13.0/build: glewinfo.rc
Files sourceforge-glew-1.13.0/build/vc6/Makefile and github-glew-glew-1.13.0/build/vc6/Makefile differ
Only in sourceforge-glew-1.13.0/build: visualinfo.rc
Only in github-glew-glew-1.13.0/: cmake-testbuild.sh
Only in sourceforge-glew-1.13.0/: include/
Only in sourceforge-glew-1.13.0/src: glew.c
Only in sourceforge-glew-1.13.0/src: glewinfo.c
```
_I was going to use this mirror in my AUR package, since SourceForge have some prolonged issues with it's servers_

**Comment by nigels-com** [comment]
It probably does make sense to go back and attach the releases for the older tags.  How far back is necessary?  Just 1.13?

**Comment by AndreiBasangiu** [comment]
I am trying to build glew on Linux. I ran into this issue as well.
I was hoping to fix the issue myself so I looked in the history of the repo quite far back and still could not find the files.
Any suggestion on how I could work around this (if possible at all)?

**Comment by nigels-com** [comment]
One alternative is: https://github.com/Perlmint/glew-cmake
