### ISSUE TITLE
Feature Request: GLEW_VERSION from glew.h

### ISSUE THREAD

**Issue by stopiccot** [nigels-com/glew#18]
GLEW_VERSION, GLEW_VERSION_MAJOR, GLEW_VERSION_MINOR, GLEW_VERSION_MICRO vars in glew_tail.h seem to have incorrect values

**Comment by nigels-com** [comment]
Yeah, I'm not really opposed to it.
But I don't want to hold up a GLEW release at the moment...

**Comment by nigels-com** [comment]
I happened across a similar feature in libpng this week.
http://sourceforge.net/p/libpng/code/ci/master/tree/png.h

Is this a good model to use?

    #define PNG_LIBPNG_VER_MAJOR   1
    #define PNG_LIBPNG_VER_MINOR   6
    #define PNG_LIBPNG_VER_RELEASE 16

**Comment by stopiccot** [comment]
yeah something like that

**Comment by stopiccot** [comment]
I've created pull request that fixes that issue in a backwards compatible way #33

**Comment by nigels-com** [comment]
Thanks for the pull request.  I put some comments over there too, do you mind revisiting this?

**Comment by nigels-com** [comment]
I put a change into github master branch.  Does it seem sufficient?

**Comment by stopiccot** [comment]
At first look it's fine. Thanks.
