### ISSUE TITLE
CMake Error at CMakeLists.txt:95

### ISSUE THREAD

**Issue by redirus** [nigels-com/glew#182]
When I tried to run the following command:
`cmake ./cmake`

CMakeLists.txt Line 88 to 95 as following
```
set (GLEW_PUBLIC_HEADERS_FILES ${GLEW_DIR}/include/GL/wglew.h ${GLEW_DIR}/include/GL/glew.h ${GLEW_DIR}/include/GL/glxew.h)
set (GLEW_SRC_FILES ${GLEW_DIR}/src/glew.c)

if (WIN32)
  list (APPEND GLEW_SRC_FILES ${GLEW_DIR}/build/glew.rc)
endif ()

add_library (glew SHARED ${GLEW_PUBLIC_HEADERS_FILES} ${GLEW_SRC_FILES})
```

no glew/include/GL/wglew.h?

**Comment by nigels-com** [comment]
It is recommend to build using the current release, rather than from git repository.

See: https://sourceforge.net/projects/glew/files/glew/2.1.0/
