### ISSUE TITLE
Cannot build in Visual Studio 2015 because glew.c is not available in src folder

### ISSUE THREAD

**Issue by zhou-heng** [nigels-com/glew#190]
I followed the (meanly) instructions [here](https://github.com/nigels-com/glew/blob/master/README.md#visual-studio). The error messages are:
```
1>------ Rebuild All started: Project: glew_static, Configuration: Release x64 ------
2>------ Rebuild All started: Project: glew_shared, Configuration: Release x64 ------
1>  glew.c
2>  glew.c
1>c1 : fatal error C1083: Cannot open source file: '..\..\src\glew.c': No such file or directory
2>c1 : fatal error C1083: Cannot open source file: '..\..\src\glew.c': No such file or directory
3>------ Rebuild All started: Project: glewinfo, Configuration: Release x64 ------
4>------ Rebuild All started: Project: visualinfo, Configuration: Release x64 ------
3>  glewinfo.c
3>c1 : fatal error C1083: Cannot open source file: '..\..\src\glewinfo.c': No such file or directory
4>  visualinfo.c
4>..\..\src\visualinfo.c(36): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory
========== Rebuild All: 0 succeeded, 4 failed, 0 skipped ==========

```
I searched all places of the downloaded package `glew-master.zip` but couldn't find `glew.c`, `glew.h` and `glewinfo.c`. The only source in `src` folder is `visualinfo.c`. So where are these source code files and how to fix the above errors?

**Comment by nigels-com** [comment]
Please download from [glew.sourceforge.net](http://glew.sourceforge.net/) rather than from github.

**Comment by zhou-heng** [comment]
Thank you for your help. I copied the vc14 folder from github package to sourceforge package and successfully built it. But I don't understand why there is no source code in github package and there is no VS2015 and 2017 project in sourceforge package. Is it hard to merge both?

**Comment by nigels-com** [comment]
The github download is just a snapshot of the GLEW repository. For general use it's recommended to use the release version that includes the generated source files, but are not tracked in git.
