### ISSUE TITLE
Unable to Download Windows Binaries

### ISSUE THREAD

**Issue by angrygoats** [nigels-com/glew#191]
Hello. It appears the link [to the sourceforge location of the binaries](https://sourceforge.net/projects/glew/files/latest/download) is giving the below error:

![image](https://user-images.githubusercontent.com/11184919/41890615-2049c62a-78c5-11e8-838e-45073c105544.png).

Is anyone else experiencing this? Is there another mirror for the binaries?

**Comment by nigels-com** [comment]
Seems OK now.  Could you try the link again?

**Comment by angrygoats** [comment]
Same problem. Tried curling it and it seems to work so apparently it's my browser? I suppose we can close this. Apologies for wasting your time.

**Comment by nigels-com** [comment]
I don't think it's a waste of time.  It seems like every time I visit SourceForge there is more and more friction, to just download a file or view a bug report.  I do still like the convenience of the download statistics, going back a long time.  But at some point it makes sense to put them all somewhere else, even if it's my personal AWS S3 bucket.
