### ISSUE TITLE
GL/glu.h no such file or directory.

### ISSUE THREAD

**Issue by babaliaris** [nigels-com/glew#192]
The first time it compiled successfull. After the first time i'm getting the error i mentioned on the title. Yes i included the path to GL root directory. GL/glew.h is being included successfully.

The problem is inside glew.h at line 1205:
```c
#ifndef GLEW_NO_GLU
/* this is where we can safely include GLU */
#  if defined(__APPLE__) && defined(__MACH__)
#    include <OpenGL/glu.h>
#  else
# include <GL/glu.h>
#  endif
#endif
```
I removed the line where it includes glu.h and now it compiles successfully and gl functions work.
I could also define GLEW_NO_GLU probably to avoid this error.

Should i restore the glu.h inclusion and then define GLEW_NO_GLU?
Can you tell me why is this error happening?

I'm in Arch Linux 64 and using code blocks to compile.

**Comment by nigels-com** [comment]
The inclusion of GLU is historical.  Presumably there are codebases that are relying on glew.h to include glu.h.  It's not needed for GLEW to build or run, but it's opt-out that reason.  I'd recommend using -DGLEW_NO_GLU since GLU is rarely seen in modern codebases nowadays.
