### ISSUE TITLE
_glewExtensionLookup is not sorted in alphabetical order

### ISSUE THREAD

**Issue by vasilvv** [nigels-com/glew#195]
GL_VERSION_4_6 goes before GL_3DFX_multisample, while it should actually go after.

This normally works just fine, since there's a dozen of versions and _a lot_ of extensions, but if you build a custom build with very few extensions listed, extension check will stop working at all because the binary search will not find any of them.

**Comment by nigels-com** [comment]
I pushed a fix for this just now.  If you could test the master branch for your use-case, that would be great!

```
...
#ifdef GL_SUN_triangle_list
  "GL_SUN_triangle_list",
#endif
#ifdef GL_SUN_vertex
  "GL_SUN_vertex",
#endif
#ifdef GL_VERSION_1_2
  "GL_VERSION_1_2",
#endif
#ifdef GL_VERSION_1_2_1
  "GL_VERSION_1_2_1",
#endif
...
```

**Comment by vasilvv** [comment]
I've tested it, and it works.  Thanks a lot!
