### ISSUE TITLE
glShaderSource: error: cannot convert 'const char*' to 'const GLchar* const*' {aka 'const char* const*'} in argument passing

### ISSUE THREAD

**Issue by siniarskimar** [nigels-com/glew#199]
Compiler error after using `glShaderSource`
`error: cannot convert 'const char*' to 'const GLchar* const*' {aka 'const char* const*'} in argument passing`

I am calling it like this
```cpp
const char* src = source.c_str();   //std::string to const char*
glShaderSource(m_glShader, 1, src, 0);
```

Looking at the glew header this 1847-th line seems wrong:
`typedef void (GLAPIENTRY * PFNGLSHADERSOURCEPROC) (GLuint shader, GLsizei count, const GLchar *const* string, const GLint* length);`

**Comment by turol** [comment]
User error, `glShaderSource` expects a pointer to an array of string pointers, you're passing it just a pointer. Try this instead:
```
glShaderSource(m_glShader, 1, &src, 0);
```

**Comment by siniarskimar** [comment]
So yeah, that was my mistake.
It works now.
