### ISSUE TITLE
OSX pkg-config missing framework declaration

### ISSUE THREAD

**Issue by reinderien** [nigels-com/glew#202]
`pkg-config` should be able to configure the linker so that all of the flags required to build against `glew` are included. For OSX (`glew` pulled via `homebrew`), that is not currently the case.

Currently, I see this output:

```
$ pkg-config --libs glew glfw3
-L/usr/local/Cellar/glew/2.1.0/lib -L/usr/local/Cellar/glfw/3.2.1/lib -lGLEW -lglfw
```

But it also needs to include:

```
-framework OpenGL
```

If this is not done, `glew` projects making use of OpenGL features will not link.

**Comment by nigels-com** [comment]
Agreed.

**Comment by nigels-com** [comment]
Fix is merged.  Can you confirm for your use-case?

**Comment by reinderien** [comment]
My use case relies on homebrew; will this patch have made it there yet?

**Comment by nigels-com** [comment]
Perhaps prompt the homebrew folks on this?
