### ISSUE TITLE
Only include increase filesize

### ISSUE THREAD

**Issue by Bubuche87** [nigels-com/glew#204]
Hello everybody.
(My english is poor, it not my mother tongue, and it's a bit late so I am tired, which does not improve that. However, I have access to the internet only during evening/night, so it is no use to delay the moment I post this).

Maybe it's a well known issue, maybe the problem is how I use glew.

The problem is : as soon as I include the "glew.h" file, the binaries produced (the ".o" file) is at least around 175kb. 

This is weird because, normally, in C, binarie's sizes do not increase with defines, typedefs etc.
They are used at compile time to produce binaries but not put in it.

It is normal that include "glew.h" in a file increases compilation time, it is not normal that it increases binary size.

To reproduce the "bug" : 
1/ create a .c file
2/ put a small function in it, compile, not link. You'll get a small .o
3/ go back to the c file, add #include <GL/glew.h> at the top of it. compile not link : BIG ~170Kb .o

Is that normal ?
I have more than one unit which uses opengl functions. And as "opengl functions" with glew are actually defines over glewContext()->__theFunctionName I can't use glew somewhere and other header (containing only function headers) somewhere else.

Is there a fix ?
Right now I workaround this problem like this, but it's far from perfect (actually : REALLY annoying)
- in a .h file I define function with the same signature as gl function except I replace gl with something else: glEnable -> yyEnable
- below, I define glEnable as yyEnable
- in a separate file I have at the top of it #include <GL/glew.h> and below functions like this void yyEnable( ... ) { glEnable( ... ); }
 
(this separate files does not "see" the defines glEnable -> yyEnable).

In this way I can have one single include of glew, and use opengl functions in a lot of files but ... that's a lot of copy-paste-edit of functions headers and a lot of troubles. And not a normal use of glew, I think.

What can I do ?

**Comment by nigels-com** [comment]
1. For the size of the .o with glew.h included, I'd expect that to be due to the numerous symbols.  What you say is generally true, but not strictly true, I think.  With gcc for example, there is quite a lot of symbolic overhead, generally.

2.  Ordinarily each compilation unit includes glew.h and can make calls, nothing further required.  Is there a particular build error that led you down this rabbit hole of wrapping a wrapper?

**Comment by nigels-com** [comment]
The struct is internal to GLEW.  There is a function pointer per entry point for the purpose of binary interface compatibility.  All this "overhead" is collapsed in the final link step, right?  Why worry about it?

**Comment by nigels-com** [comment]
> I also tried to manually load functions myself ... but then I get a crash

On Windows watch out for the stdcall vs c-call calling convention stuff.  It has to do with whether it's the caller or the function that unwinds the stack on exit.

**Comment by nigels-com** [comment]
If Mingw provides the **nm** tool, try that for inspecting the GLEW symbols for a .o file.

Not just the functions, but also the GL version and extension enable runtime flags.

```
...
000000000029cfe0 B __glewActiveStencilFaceEXT
000000000029da98 B __glewActiveTexture
00000000002a4928 B __glewActiveTextureARB
00000000002a1ea8 B __glewActiveVaryingNV
000000000029c4f0 B __glewAddressSpace
...
00000000002a3590 B __GLEW_VERSION_4_0
00000000002a0b30 B __GLEW_VERSION_4_1
000000000029d968 B __GLEW_VERSION_4_2
00000000002a58b0 B __GLEW_VERSION_4_3
00000000002a2f70 B __GLEW_VERSION_4_4
...
000000000029f848 B __GLXEW_SGI_make_current_read
000000000029e9c0 B __GLXEW_SGIS_blended_overlay
00000000002a0740 B __GLXEW_SGIS_color_range
000000000029c878 B __GLXEW_SGIS_multisample
00000000002a1a88 B __GLXEW_SGIS_shared_multisample
00000000002a3768 B __GLXEW_SGI_swap_control
000000000029dcf8 B __GLXEW_SGI_video_sync
```

But they seem harmless to me.

**Comment by Bubuche87** [comment]
Wow thanks a lot for all of this. Especially the thing with stdcall, it may come from here.
About the size ... my compilation produces several compilation unit (.o) stored into an archive (.a or .lib) which is linked with the main.c in the final step. 
Somehow the size of the exe produced this way is bigger when I include glew in several compilation units. I use this process for years, without having any problem with it. Maybe this came to an end. 

I will investigate in this stdcall thing. 

Also

```
000000000029cfe0 B __glewActiveStencilFaceEXT
000000000029da98 B __glewActiveTexture
```

This is weird, isn't it ? If you have a file like this

```
struct something
{
  int a;
  int b;
  ...
};

struct something BLA;

```

You should have only one symbol in the .o ("BLA"). 
You shoudn't have see "a" and "b" in the .o. 
And if it is "extern struct something BLA;" it's even better, cause you should now only have one "request for symbol at link time". 
Now, if "a" and "b" are pointers to functions, you'll be able to write 

`BLA.a(parameter1, parameter2 ...)`

And with a smart define like this

```
#define a_function (BLA.a)
#define b_function (BLA.b)
```

you can write 

```
a_function(parameter1 ...)
b_function(parameter2 ...)
```

And you can have 1000 functions, with only one single symbol exported after the inclusion of the .h
(And there is nothing magic in this : by giving the struct you force all of these functions to be at a precise place "starting at BLA". By resolving one symbol you resolve all of them, with the cost of copying function's addresses in correct locations at runtime - what you have to do anyway with opengl).

I will investigate this problem with the tool you mentioned "nm".

Thanks a lot and sorry for the too long post, I like to talk :smile:

**Comment by nigels-com** [comment]
I wonder if this is some sort of quirk of the Mingw toolchain.  I tried this on Linux, but didn't see a large .o just for including glew.h.

GLEW 1.13.0 has MX mode using a struct along the lines of what you're describing.  But that mode was dropped into GLEW 2.0.0 for internal reasons.  (Difficult to maintain)

One possible solution is to link GLEW statically.  Try building with -DGLEW_STATIC=1 and see if that is any better.

**Comment by Bubuche87** [comment]
Sorry for not answering yesterday.
nm didn't bring anything usefull (just a bunch of symbols, the problem is not from here).

For the record, I put two files with this message (in a zip, the website doesn't not allow me to upload .o files)
The .c file is either empty or containing only the include for glew.

[example.zip](https://github.com/nigels-com/glew/files/2743189/example.zip)

I don't know if this can be usefull, but at least it's something solid to talk about.

**Comment by nigels-com** [comment]
How does the output of nm differ in the two scenarios?  How many lines are there?

**Comment by Bubuche87** [comment]
Voici le résultat du nm pour les deux fichiers que j'avais link

```
C:\Users\YeoYin\_2D>nm "F:/glewbug/sample_with_glew.o"
00000000 b .bss
00000000 d .data
00000000 N .debug_abbrev
00000000 N .debug_aranges
00000000 N .debug_info
00000000 N .debug_line
00000000 r .rdata$zzz
00000000 t .text

C:\Users\YeoYin\_2D>nm "F:/glewbug/sample_without_glew.o"
00000000 b .bss
00000000 d .data
00000000 r .rdata$zzz
00000000 t .text

C:\Users\YeoYin\_2D>
```
