### ISSUE TITLE
ptrdiff_t undefined

### ISSUE THREAD

**Issue by Gh0stBlade** [nigels-com/glew#219]
I'm having difficulty using GLEW 2.1.0 on Mac OS X High Sierra 10.13.
![glew](https://user-images.githubusercontent.com/6951235/53859213-e8a11c00-3fd4-11e9-953d-7cddd38ab3d1.png)
 
For some reason ptrdiff_t is undefined causing serious errors, I attempted to include <stddef.h> with no luck.
Can someone help me please?
Thanks.

**Comment by nigels-com** [comment]
Some more context might help on this.

What are the compilation flags?

Apple toochain or another one?

Is the broader project on github?

**Comment by Gh0stBlade** [comment]
The only compiler flags I've set are: -Wno-narrowing -std=c++11

I'm using GCC 8.3.0 toolchain from Homebrew. https://formulae.brew.sh/formula/gcc

GitHub project: https://github.com/TOMB5/TOMB5/tree/develop-gh0stblade

**Comment by Gh0stBlade** [comment]
I've tried GCC 4.9 as well, same issue. Any idea on what I could be doing wrong?

**Comment by nigels-com** [comment]
If you're building in c++ mode, it might help to hack the header to refer to 'std::ptr_diff'.

**Comment by Gh0stBlade** [comment]
I've had no problems with GLEW 2.1.0 under Linux using the same compiler flags but I will try what you suggested :)

**Comment by nigels-com** [comment]
sorry, I mean to say: `std::ptrdiff_t`

(Based on what I see over at https://en.cppreference.com/w/cpp/types/ptrdiff_t)

**Comment by nigels-com** [comment]
I was able to reproduce and resolve this on osx macOS Mojave, building the TOMB5/TOMB5 repo.

In glew.h, replace the block of preprocesser from the <stddef.h> include with:
```
#if defined(__APPLE__)
#  if defined(__cplusplus)
#    include <cstddef>
#    include <cstdint>
#  else
#    include <stddef.h>
#    include <stdint.h>
#  endif
#else

# include <stddef.h>

/* SGI MIPSPro doesn't like stdint.h in C++ mode          */
/* ID: 3376260 Solaris 9 has inttypes.h, but not stdint.h */

#  if (defined(__sgi) || defined(__sun)) && !defined(__GNUC__)
#    include <inttypes.h>
#  else
#    include <stdint.h>
#  endif
#endif
```

**Comment by Gh0stBlade** [comment]
Can confirm this fixes the issue. Thank you.

**Comment by nigels-com** [comment]
Great!  Thanks.
