### ISSUE TITLE
Using glew 2.1.0 with Windows 64-bit and MinGW

### ISSUE THREAD

**Issue by brunomrsn** [nigels-com/glew#223]
I had many problems trying to use this library:

1) The binary comes with .lib files, so I couldn't run in CodeBlocks, VS Code or Eclipse, this only works in Visual Studio.
2) I found out I had to compile the glew source code, but using the steps from [https://github.com/nigels-com/glew] didn't work.

Then, for those who couldn't solve, this is the solution:

1) Download the sources and unzip them.
2) Open CMD (PowerShell has problems with the commas in the commands).
3) Enter the glew unziped folder (using cd command).
4) Execute each of these commands one by one:

- mkdir lib/
- mkdir bin/
- gcc -DGLEW_NO_GLU -O2 -Wall -W -Iinclude  -DGLEW_BUILD -o src/glew.o -c src/glew.c
- gcc **-nostdlib** -shared -Wl,-soname,libglew32.dll -Wl,--out-implib,lib/libglew32.dll.a -o lib/glew32.dll src/glew.o -L/mingw/lib -lglu32 -lopengl32 -lgdi32 -luser32 -lkernel32
- ar cr lib/libglew32.a src/glew.o
- gcc -DGLEW_NO_GLU -DGLEW_MX -O2 -Wall -W -Iinclude  -DGLEW_BUILD -o src/glew.mx.o -c src/glew.c
- gcc **-nostdlib** -shared -Wl,-soname,libglew32mx.dll -Wl,--out-implib,lib/libglew32mx.dll.a -o lib/glew32mx.dll src/glew.mx.o -L/mingw/lib -lglu32 -lopengl32 -lgdi32 -luser32 -lkernel32
- ar cr lib/libglew32mx.a src/glew.mx.o

5) Finally, copy the generated **.a** files to MinGW's **lib** folder, the **.h** files to MinGW's **include/GL** folder and the **.dll** files to SystemWOW (for 64-bit), then setup the compiler options to load the libraries.

If you want to build visualinfo as well:

- gcc -c -O2 -Wall -W -Iinclude  -o src/glewinfo.o src/glewinfo.c
- gcc -O2 -Wall -W -Iinclude  -o bin/glewinfo.exe src/glewinfo.o -Llib  -lglew32 -L/mingw/lib -lglu32 -lopengl32 -lgdi32 -luser32 -lkernel32
- gcc -c -O2 -Wall -W -Iinclude  -o src/visualinfo.o src/visualinfo.c
- gcc -O2 -Wall -W -Iinclude  -o bin/visualinfo.exe src/visualinfo.o -Llib  -lglew32 -L/mingw/lib -lglu32 -lopengl32 -lgdi32 -luser32 -lkernel32

OBS.: Many solutions I searched for didn't work because of the **-nostdlib** parameter missing, so that did the trick, at least for me. Some solutions say to add **#define GLEW_STATIC** before including the "GL/glew.h", but that wasn't necessary.

Good luck.

**Comment by nigels-com** [comment]
That looks aligned with what `make SYSTEM=mingw` is doing.
Take a look at `config/Makefile.mingw` for the details.

**Comment by DJ-Dav** [comment]
some of the commands flood the terminal with:
`src/glew.c:19534:34: warning: cast between incompatible function types from 'PROC' {aka 'long long int (*)()'} to 'const char * (*)(void)' [-Wcast-function-type]
19534 |   _wglewGetExtensionsStringEXT = (PFNWGLGETEXTENSIONSSTRINGEXTPROC)glewGetProcAddress((const GLubyte*)"wglGetExtensionsStringEXT");`
Any clue what this means?

**Comment by nigels-com** [comment]
> some of the commands flood the terminal with: `src/glew.c:19534:34: warning: cast between incompatible function types from 'PROC' {aka 'long long int (*)()'} to 'const char * (*)(void)' [-Wcast-function-type] 19534 | _wglewGetExtensionsStringEXT = (PFNWGLGETEXTENSIONSSTRINGEXTPROC)glewGetProcAddress((const GLubyte*)"wglGetExtensionsStringEXT");` Any clue what this means?

It's a legit warning, to be expected.
