### ISSUE TITLE
error: "something" redeclared

### ISSUE THREAD

**Issue by bothie** [nigels-com/glew#225]
I'm getting a bunch of errors between glext.h and glew.h. I remember, this isn't the first time. So, my questions is:

```
#if defined(__gl_h_) || defined(__GL_H__) || defined(_GL_H) || defined(__X_GL_H)
#error gl.h included before glew.h
#endif
#if defined(__gl2_h_)
#error gl2.h included before glew.h
#endif
#if defined(__gltypes_h_)
#error gltypes.h included before glew.h
#endif
#if defined(__REGAL_H__)
#error Regal.h included before glew.h
#endif
#if defined(__glext_h_) || defined(__GLEXT_H_)
#error glext.h included before glew.h
#endif
#if defined(__gl_ATI_h_)
#error glATI.h included before glew.h
#endif

#define __gl_h_
#define __gl2_h_
#define __GL_H__
#define _GL_H
#define __gltypes_h_
#define __REGAL_H__
#define __X_GL_H
#define __glext_h_
#define __GLEXT_H_
#define __gl_ATI_h_
```

Why is this in glew.h. Why isn't there what there SHOULD be:

```
#include <GL/gl.h>
#include <GL/gl2.h>
#include <GL/gltypes.h>
#include <GL/Regal.h>
#include <GL/glext.h>
#include <GL/glATI.h>
```

**Comment by nigels-com** [comment]
Generally speaking, glew.h replaces (and conflicts with) those other headers.  The fix is to use GLEW and not try to mix with those .

**Comment by bothie** [comment]
The question was "Why?" Please explain it to me.

**Comment by nigels-com** [comment]
`glext.h` and GLEW overlap to a significant extent.  They're providing (mostly) the same typedefs.  But GLEW does not depend on `glext.h` or necessarily match exactly what's there.

So typically a codebase is using GLEW everywhere, or nowhere, for this reason.

**Comment by bothie** [comment]
Thank you for taking your time for trying to answer my question.

Sadly, the only thing you're telling me, is, what I already know: "That" GLEW does, what it does. My question was "Why" does GLEW do it this way. There has to be a fundamental reason behind it. What is it?

**Comment by nigels-com** [comment]
In a nutshell GLEW is providing all of the OpenGL API with the convenience of one #include.  It's not trying to coexist with the various other ways of binding to OpenGL.
