### ISSUE TITLE
MX is still referenced in documentation with 2.1.0

### ISSUE THREAD

**Issue by KBentley57** [nigels-com/glew#226]
Hi all,

I have been trying to build the Mitsuba renderer, which requires libGLEWmx.  I grabbed the 2.1.0 release, and started to build, but I kept getting "No rule to make target install.mx" type errors.  I see from the discussions that MX was dropped as early as 2.0.0.  Is that correct?  If so, the documentation could use a bit of cleaning up to prevent a similar misunderstanding.

Thanks,

Kyle

**Comment by nigels-com** [comment]
Hello Kyle,

In principle I'd be willing to continue releasing 1.3.x bugfix releases for MX.  So I'll review the documentation to see if that can be clarified as a "legacy" option.

- Nigel

**Comment by KBentley57** [comment]
That sounds like a good option.  Thanks for looking into it!

Kyle
