### ISSUE TITLE
OpenGL and GLEW displays with flat colors

### ISSUE THREAD

**Issue by TomPandolfi** [nigels-com/glew#229]
Shading was working with OpenGL and freeGLUT, except the whole program closed when I closed the OpenGL window. I found several articles about how to fix this problem, but none of them worked. I switched from freeGLUT to GLEW and that solved my window problem. But something got lost in the translation and now my 3D objects are drawn in a single flat color. I can control the color but all the faces are the same color - no shading. 

![flat torus](https://user-images.githubusercontent.com/2965348/57987803-a156f300-7a3b-11e9-9201-dadd5401d42f.jpg)

**Comment by nigels-com** [comment]
Is the program a fixed-function one, or using shaders?  Is there GL error checking that reveals anything more specific?
