### ISSUE TITLE
stable release schedule

### ISSUE THREAD

**Issue by maxbla** [nigels-com/glew#232]
I had an issue [compiling a program](https://aur.archlinux.org/packages/tome4/) that uses glew. I switched to a version of glew based on the git master branch. The program then compiled properly. I appreciate you constantly improving glew, but I wonder when another stable release is possible. It seems like the [last one](http://glew.sourceforge.net/log.html) was in 2017.

**Comment by nigels-com** [comment]
Indeed.  It's well past time for a release.

**Comment by nigels-com** [comment]
Christmas 2019.
