### ISSUE TITLE
where is glew.c

### ISSUE THREAD

**Issue by kingofthebongo2008** [nigels-com/glew#233]
I have tried to build windows versions and this file is missing in git

**Comment by nigels-com** [comment]
It's recommended to download the release tgz or zip, rather than from-scratch from git repo.
See: http://glew.sourceforge.net/

**Comment by k6l2** [comment]
Lol... What is this nonsense?  What's the point of even having the solution file in the first place if we can't even build it?

**Comment by nigels-com** [comment]
There is a fresh dev build here, if it helps:
https://s3.amazonaws.com/glew/nigels-com/glew/380/380.1/glew-2.2.0.zip

Or perhaps: https://github.com/Perlmint/glew-cmake

**Comment by k6l2** [comment]
I mean that's great and all, but is there an explanation for why this repository no longer contains the glew source?

**Comment by nigels-com** [comment]
Ah, the GLEW repo has always been concerned about _generating_ the source, but not tracking the history of what is generated.

**Comment by kingofthebongo2008** [comment]
ok, thanks,
