### ISSUE TITLE
Put CMake config file in a subdirectory or name it glew-config.cmake.in to avoid confusion

### ISSUE THREAD

**Issue by gracicot** [nigels-com/glew#234]
The [`build/cmake`](https://github.com/nigels-com/glew/tree/master/build/cmake) directory contains the `glew-config.cmake` directly side by side to the main `CMakeLists.txt`.

When Setting `glew_DIR` or `CMAKE_PREFIX_PATH` to this path, CMake will happily include that file and cause multiple error. [Here's a user that got confused with the errors generated](https://stackoverflow.com/q/57484108/2104697).

There should be no file named `glew-config.cmake` directly in the main source directory. Instead, it should be named `glew-config.cmake.in` (and call configure on it) or place it in a subfolder, like `config-file/glew-config.cmake`

**Comment by gracicot** [comment]
Sorry for the noise, I just saw that GLEW don't support importation from the build tree, unless I'm misaken again.

**Comment by nigels-com** [comment]
Ah, not that I know of.  GLEW is a bit unusual in that it's more concerned about generating source code than dropping straight into a project as a submodule.
