### ISSUE TITLE
const missing from glMultiDrawElementsBaseVertex glew.h

### ISSUE THREAD

**Issue by Sknowman** [nigels-com/glew#235]
The use of const for 3 args is missing from glMultiDrawElementsBaseVertex
glew.h line 4600 from glew-2.1.0-win32.zip

typedef void (GLAPIENTRY * PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC) (GLenum mode, GLsizei* count, GLenum type, void**indices, GLsizei primcount, GLint *basevertex);

https://www.khronos.org/opengl/wiki/GLAPI/glMultiDrawElementsBaseVertex
(https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glMultiDrawElementsBaseVertex.xhtml)

void glMultiDrawElementsBaseVertex(GLenum mode, const GLsizei *count, GLenum type,
const GLvoid * const *indices, GLsizei drawcount, const GLint *basevertex);

**Comment by nigels-com** [comment]
Confirming that.  I filed an upstream fix for [KhronosGroup/OpenGL-Registry](https://github.com/KhronosGroup/OpenGL-Registry)

If you need an updated tgz or zip, let me know, I'll upload a fresh snapshot.

**Comment by nigels-com** [comment]
Took some upstream wrangling, looks like it's on the right track.

**Comment by nigels-com** [comment]
Looking good for a fresh GLEW generated from master branch.
Can you confirm and/or test?

```
/* -------------------- GL_ARB_draw_elements_base_vertex ------------------- */

#ifndef GL_ARB_draw_elements_base_vertex
#define GL_ARB_draw_elements_base_vertex 1

typedef void (GLAPIENTRY * PFNGLDRAWELEMENTSBASEVERTEXPROC) (GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
typedef void (GLAPIENTRY * PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC) (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
typedef void (GLAPIENTRY * PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC) (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
typedef void (GLAPIENTRY * PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC) (GLenum mode, const GLsizei* count, GLenum type, const void*const *indices, GLsizei drawcount, const GLint *basevertex);

#define glDrawElementsBaseVertex GLEW_GET_FUN(__glewDrawElementsBaseVertex)
#define glDrawElementsInstancedBaseVertex GLEW_GET_FUN(__glewDrawElementsInstancedBaseVertex)
#define glDrawRangeElementsBaseVertex GLEW_GET_FUN(__glewDrawRangeElementsBaseVertex)
#define glMultiDrawElementsBaseVertex GLEW_GET_FUN(__glewMultiDrawElementsBaseVertex)

#define GLEW_ARB_draw_elements_base_vertex GLEW_GET_VAR(__GLEW_ARB_draw_elements_base_vertex)

#endif /* GL_ARB_draw_elements_base_vertex */

```
