### ISSUE TITLE
declaration of 'n' hides previous local declaration

### ISSUE THREAD

**Issue by XZiar** [nigels-com/glew#240]
https://github.com/nigels-com/glew/blob/ea30c83d92044d5291f6e669ecdd2dfc8dbfd1d8/auto/src/glew_init_gl.c#L132-L140

https://github.com/nigels-com/glew/blob/ea30c83d92044d5291f6e669ecdd2dfc8dbfd1d8/auto/src/glew_init_gl.c#L80-L85

Line 138 re-declare variable `n`, which was previously declared at line 82.

It should not lead to any bug but maybe consider change its name?

**Comment by nigels-com** [comment]
What particular compiler/version is complaining about this?

**Comment by XZiar** [comment]
VS2019, when compiling with `W4`

Error message is here https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4456?view=vs-2019

**Comment by turol** [comment]
You can make GCC and clang show a similar message by passing `-Wshadow`

**Comment by nigels-com** [comment]
I pushed a change to resolve this for gcc 7.4.0 with `-Wshadow`
Most likely this will make the MS compiler happy too.
