### ISSUE TITLE
-nostdlib 

### ISSUE THREAD

**Issue by galloperico** [nigels-com/glew#242]
In mingw, why -nostdlib flag is used for linking?, this makes linking fail with multiple "undefined reference" errors from fprint, strcmp, etc. If I delete this flag linking can be completed.

**Comment by nigels-com** [comment]
Fixed in the upcoming release.

There is a snapshot available for confirmation purposes:
https://sourceforge.net/projects/glew/files/glew/snapshots/glew-20190928.tgz/download
