### ISSUE TITLE
Confusing/Incorrect argument names for glStencilFuncSeparate

### ISSUE THREAD

**Issue by heyx3** [nigels-com/glew#243]
The docs for glStencilFuncSeparate state that the first argument determines whether the function is about front-faces or back-faces, and the second argument is the stencil test to use for those faces.

However, in GLEW those two arguments come up with the names "frontfunc" and "backfunc", implying that you're supposed to set *both* front- and back-face tests in one function call.

https://www.khronos.org/opengl/wiki/GLAPI/glStencilFuncSeparate

**Comment by nigels-com** [comment]
glew.h

```
typedef void (GLAPIENTRY * PFNGLSTENCILFUNCSEPARATEPROC) (GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask);
```

gl.xml

```
        <command>
            <proto>void <name>glStencilFuncSeparate</name></proto>
            <param group="StencilFaceDirection"><ptype>GLenum</ptype> <name>face</name></param>
            <param group="StencilFunction"><ptype>GLenum</ptype> <name>func</name></param>
            <param group="StencilValue"><ptype>GLint</ptype> <name>ref</name></param>
            <param group="MaskedStencilValue"><ptype>GLuint</ptype> <name>mask</name></param>
        </command>
```

Indeed, the misnaming seems to stem from wording for `glStencilFuncSeparateATI` from that specification, (that might need correction).

https://www.khronos.org/registry/OpenGL/extensions/ATI/ATI_separate_stencil.txt

I certainly agree that `glStencilFuncSeparate` ought to align with the XML parameter names.

**Comment by nigels-com** [comment]
Appears to have been this way since 2004

```
commit 47e028ae2656b071ec6d86470b7ff70f00a35440
Author: ikits <ikits@783a27ee-832a-0410-bc00-9f386506c6dd>
Date:   Thu Dec 30 02:59:44 2004 +0000

    added core 2.0 spec file
```

**Comment by nigels-com** [comment]
Fixed, thanks for the report.
