### ISSUE TITLE
Unable to open a no error context.

### ISSUE THREAD

**Issue by Eybor** [nigels-com/glew#248]
Hello,
I was trying to open a no error OpenGL context but the defines WGL_CONTEXT_OPENGL_NO_ERROR_ARB and GLX_CONTEXT_OPENGL_NO_ERROR_ARB are missing in wglew.h and glxew.h respectively. See [this extension](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_create_context_no_error.txt). Is it possible to fix this?

**Comment by nigels-com** [comment]
Looks like it's there in the release candidate, could you confirm?

https://sourceforge.net/projects/glew/files/glew/snapshots/glew-20190928.tgz/download

```
$ rgrep CONTEXT_OPENGL_NO_ERROR_ glew-2.2.0
glew-2.2.0/include/GL/glxew.h:#define GLX_CONTEXT_OPENGL_NO_ERROR_ARB 0x31B3
glew-2.2.0/include/GL/eglew.h:#define EGL_CONTEXT_OPENGL_NO_ERROR_KHR 0x31B3
glew-2.2.0/include/GL/wglew.h:#define WGL_CONTEXT_OPENGL_NO_ERROR_ARB 0x31B3
```

**Comment by Eybor** [comment]
Sorry for the late reply, it does work now thanks for your quick fix.

**Comment by nigels-com** [comment]
All good, thanks for the report.
