### ISSUE TITLE
GL_EXT_semaphore is missing some constants

### ISSUE THREAD

**Issue by malte-v** [nigels-com/glew#249]
From the registry: (https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_external_objects.txt):

>     If the GL_EXT_semaphore string is reported, the following tokens are
>     added:
> 
>     Accepted by the <dstLayouts> parameter of SignalSemaphoreEXT and the
>     <srcLayouts> parameter of WaitSemaphoreEXT:
> 
>         LAYOUT_GENERAL_EXT                            0x958D
>         LAYOUT_COLOR_ATTACHMENT_EXT                   0x958E
>         LAYOUT_DEPTH_STENCIL_ATTACHMENT_EXT           0x958F
>         LAYOUT_DEPTH_STENCIL_READ_ONLY_EXT            0x9590
>         LAYOUT_SHADER_READ_ONLY_EXT                   0x9591
>         LAYOUT_TRANSFER_SRC_EXT                       0x9592
>         LAYOUT_TRANSFER_DST_EXT                       0x9593
>         LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_EXT 0x9530
>         LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_EXT 0x9531

These constants are in the `GL_EXT_memory_objects` file, not in `GL_EXT_semaphore`, where they belong. Also, the last two constants appear to be missing.

**Comment by nigels-com** [comment]
Yes, I think you're right.

**Comment by nigels-com** [comment]
Here is s snapshot with the change applied.
https://s3.amazonaws.com/glew/nigels-com/glew/413/413.1/glew-2.2.0.tgz

**Comment by malte-v** [comment]
Thanks for the quick fix! Everything looks right now.
