### ISSUE TITLE
git clone and cmake not working.

### ISSUE THREAD

**Issue by makarenya** [nigels-com/glew#254]
I can't build with cmake fresh git repo.
A I can't find this files in this folders. 
So i can't make glew as subrepo of my project...

CMake Error at CMakeLists.txt:183 (add_executable):
  Cannot find source file:

    /Users/me/projects/glew/src/glewinfo.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:111 (add_library):
  Cannot find source file:

    /Users/me/projects/glew/include/GL/wglew.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

**Comment by nigels-com** [comment]
The repository tracks the code generation, but not the code itself.

Perhaps try:
https://github.com/Perlmint/glew-cmake

**Comment by nigels-com** [comment]
The recommended path is to fetch the current release, or pre-release snapshot:

https://github.com/nigels-com/glew#recent-snapshots
