### ISSUE TITLE
glxew.h requires X1 headers

### ISSUE THREAD

**Issue by AlaAyesh** [nigels-com/glew#256]
The glxew,h is requiring to include X1 headers and this is over Microsoft windows. So how can I fix that?

**Comment by nigels-com** [comment]
If the code is unconditionally including `glxew.h` it's a strong hint that the code doesn't support Windows.

**Comment by AlaAyesh** [comment]
But I am installing the windows glew package?

**Comment by nigels-com** [comment]
Please provide some more details of what is expected, and what is observed, including step-by-step to reproduce.  Thanks.

**Comment by AlaAyesh** [comment]
Thanks. I am trying to use glew library to use glx function calls on Windows but even though I am installing the windows version when I try to include glxew.h it asks to include X1 headers? So what is wrong?
