### ISSUE TITLE
glShadingRateSampleOrderNV missing from NV_shading_rate_image

### ISSUE THREAD

**Issue by MegaManSE** [nigels-com/glew#260]
NV_shading_rate_image is missing the ShadingRateSampleOrderNV function.  It is listed in the text of the spec but there appears to be a typo in the spec missing the function in the formal list: https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shading_rate_image.txt

The spec is a bit confusing because it's listed as a function in there but not in the list of functions.  I'm going to also reach out to the NVidia contact to update the spec to properly list this function.

**Comment by nigels-com** [comment]
Confirming that this is missing from GLEW 2.2.0, the current release.
Appears to be available in master branch, now.
Good candidate for a GLEW 2.2.1 release then.
