### ISSUE TITLE
glew-2.2.0 tag is missing

### ISSUE THREAD

**Issue by jbeich** [nigels-com/glew#262]
Looks like SF mirror already hosts 2.2.0. Downstream may want to know which commit the release corresponsd to (e.g., reproducibility, bisecting).

https://sourceforge.net/projects/glew/files/glew/2.2.0/

**Comment by nigels-com** [comment]
Fair enough.  I got partway into doing the release process, then paused it.

**Comment by andyrtr** [comment]
So is it out and should be packaged or better wait until a final announcement happens?

**Comment by nigels-com** [comment]
It's released, I just have the admin to catch up on.  Any fixes would be 2.2.1.

**Comment by lgbaldoni** [comment]
Also is there a changelog somewhere?

**Comment by ShFil119** [comment]
@nigels-com can you release it? There's kinda weird situation with ubuntu, 20.04 doesn't have 32 bit libs and 18.04 has buggy release.

**Comment by marv** [comment]
What's the status on this? I'd love to update to 2.2.0 on Exherbo and we'd use a proper release tarball from github preferably

**Comment by akien-mga** [comment]
Bump. This should be fairly simple to address:
```
git tag glew-2.2.0 9fb23c3e61cbd2d581e33ff7d8579b572b38ee26
git push --tag
```

Many distros rely on https://release-monitoring.org/project/7878/ to give them reports on which packages are in need of update, and GLEW shows up as one where distros might typically have a newer version than upstream (if they did notice the 2.2.0 release by another mean), which is a red flag.

**Comment by nigels-com** [comment]
Done, pushed.
