### ISSUE TITLE
Pop!_OS build impossible glew.c

### ISSUE THREAD

**Issue by johhnry** [nigels-com/glew#269]
Hi,

I am using Pop!_OS 19.10 (highly derived from Ubuntu) and I installed the build tools (`sudo apt-get install build-essential libxmu-dev libxi-dev libgl-dev`)

I just downloaded the latest version of glew (2.1.0 with `git clone`) and when I run `make`, here is the output : 

```sh
@pop-os:~/Documents/opengl/glew$ make
make: ***  No Rule found to build « src/glew.c », needed to build « tmp/linux/default/shared/glew.o ». Finish.
```

Maybe it's a duplicate of this issue https://github.com/nigels-com/glew/issues/90 but the answer doesn't solve the problem.

What is wrong here?

Thanks

**Comment by nigels-com** [comment]
https://github.com/nigels-com/glew#build

> It is highly recommended to build from a tgz or zip release snapshot. The code generation workflow is a complex brew of gnu make, perl and python, that works best on Linux or Mac.

Latest release is:
https://sourceforge.net/projects/glew/files/glew/2.2.0/

**Comment by johhnry** [comment]
Ok my bad, sorry for the duplicate.

Have a nice day!
