### ISSUE TITLE
Different compiler flags /MDd and /MT for Debug and Release for Visual Studio.

### ISSUE THREAD

**Issue by VitaliiGitHub** [nigels-com/glew#272]
For project **glew_static**, **Release** building with flag **/MT** and **Debug** with flag **/MDd**. Why Debug is use /MDd? It would be more logical /MTd.

The problem arose in one of my projects where I got an error in Debug/x86 mode:

1>LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
1>MSVCRTD.lib(_chandler4gs_.obj) : error LNK2019: unresolved external symbol __except_handler4_common referenced in function __except_handler4

I can add 'MSVCRTD' to Linker->Input->Ignored Specific Default Libraries but perhaps more better will be build **glew_static** **with** **flags /MT(Release) and /MTd(Debug) ?**

**Comment by nigels-com** [comment]
>  It would be more logical /MTd

Can you expand on the pros and cons of /MDd and /MTd ?

Presumably it's been this way for a long and changing it will likely break widely.

**Comment by VitaliiGitHub** [comment]
https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/abx4dbyh(v=vs.120)?redirectedfrom=MSDN

**Comment by nigels-com** [comment]
Oh, I'd say for static linking you're always going to need to align these flags for CRT purposes.  That's the way it is on Windows, as I understand it.  I'm not sure it's a matter of what is better or more logical, different options for different circumstances.

**Comment by VitaliiGitHub** [comment]
I agree, if necessary, someone will correct it. I ran into a problem that the release for Windows do not work for me fully. I needed to rebuild the project of GLEW with the flags I needed.
