### ISSUE TITLE
Please clarify releases 2.2.0 from github vs sourceforge

### ISSUE THREAD

**Issue by gitbearflying** [nigels-com/glew#290]
Gentoo https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/glew/glew-2.2.0.ebuild and arch https://github.com/archlinux/svntogit-packages/blob/packages/glew/trunk/PKGBUILD use the release 2.2.0 from 2020-03-16 located at https://sourceforge.net/projects/glew/files/glew/2.2.0/ .
This seems to be wrong, and https://github.com/nigels-com/glew/releases/tag/glew-2.2.0 should be used, right?

Can someone please clarify how the release 2.2.0 on sourceforge happend to be there?
It should probably be removed to avoid confusion.

**Comment by nigels-com** [comment]
They're the same, I'm just switching over the primary hosting from sourceforge to github.
Sorry for any confusion, yes, (ideally) migrate to the github links.

**Comment by nigels-com** [comment]
My general intention is to use github going forward.  But I do have an S3 copy also, just in case.
It looks like I made a bit of a mess of the GLEW 2.2.0 release because not all the usual steps happened.
So, I'm looking to simplify the workflow where I can.

**Comment by gitbearflying** [comment]
Thanks for clarification.
