### ISSUE TITLE
Cannot build via cmake because some files do not exist

### ISSUE THREAD

**Issue by Miyy** [nigels-com/glew#291]
```
src/glewinfo.c
include/GL/wglew.h
build/visualinfo.rc
```

These files do not exist in the latest version (2.2.0) of github repository. They do exist in sourceforge 2.1.0 sources though.

Please fix this issue so it could be possible to clone the repo from github and build it by cmake.

**Comment by nigels-com** [comment]
Try: https://github.com/Perlmint/glew-cmake

**Comment by nigels-com** [comment]
See Issue #13

**Comment by Bktero** [comment]
This is painful... :(

**Comment by Sebanisu** [comment]
I was attempting to fix cmake https://github.com/Sebanisu/glew/tree/patch-1.
Though I got it to run cmake the build didn't work. My fault I didn't know the deal with this repo.

I now see this stuff here.

Maybe you could deprecate or remove the old cmakelists.txt and add https://github.com/Perlmint/glew-cmake to the readme.md for those who want to use cmake. Maybe even for those who want to use visual studio.
