### ISSUE TITLE
Linker warning with pre-built binaries on Windows

### ISSUE THREAD

**Issue by toptensoftware** [nigels-com/glew#296]
On Windows, when linking to the static version of glew, the linker emits the following warning:

~~~
glew32s.lib(glew.obj) : warning LNK4099: PDB 'vc120.pdb' was not found with 'glew32s.lib(glew.obj)' or at 'C:\Users\Brad\Projects\zmach\frontends\win\bin\debug\vc120.pdb'; linking object as if no debug info
~~~

It's a benign warning because I doubt there's much need to step into glew, but it's annoying none-the-less.

Any chance we can have the .pdb files included in the binary download package?

**Comment by nigels-com** [comment]
(If I recall correctly) The PDB debug files are specific to the compiler version, so it would be cumbersome to include these, and would be a moving target.  Fortunately there is rarely any need to debug GLEW, as you point out.

**Comment by toptensoftware** [comment]
Ah ok, that makes sense.  fwiw: I worked around it with a `/IGNORE:4099` switch to the linker.
