### ISSUE TITLE
Error after glewInit() for OpenGL 3.2 and above with SDL2 - Core context

### ISSUE THREAD

**Issue by lemanyk** [nigels-com/glew#3]
Here is my code http://pastie.org/8392206

Compile was success, but then on run it fails with error "invalid enumerant"

**Comment by GuapoTaco** [comment]
Running a similar app under gDEBugger, it says that the error is on glGetString(GL_EXTENSIONS), which is a deprecated function.

**Comment by karolherbst** [comment]
well now divinitiy original sin triggeres that with mesa drivers

**Comment by nigels-com** [comment]
Probably resolved with GLEW 2.0.0, closing.
Thanks for the report.
