### ISSUE TITLE
Glew-2.2.0 looking for non-existent sudirectory 

### ISSUE THREAD

**Issue by afernandezody** [nigels-com/glew#303]
Hello,
I've installed glew-2.2.0 in a CentOS8 system. It has built the library but the weird part is that, while doing so, it includes `-L/usr/X11R6/lib64`, which doesn't exist. The standard libraries are built at `/usr/lib64`. The config.guess executable is returning `x86_64-pc-linux-gnu` so I'm not sure why it's trying to include libraries at the non-existent subdirectory. Any suggestion or explanation would be more than welcomed. Thanks.

**Comment by nigels-com** [comment]
Adjust that as necessary, `config.guess` isn't specific enough for all variations.
cmake can also be worth a try.
