### ISSUE TITLE
Don't strip binaries by default

### ISSUE THREAD

**Issue by rossburton** [nigels-com/glew#310]
Distributions want to stage unstripped binaries and handle splitting out the debug symbols themselves.  `make install` forcibly calling `install -s` makes this impossible.

Yocto patches out the `-s`.  Debian does `export INSTALL=install --strip-program=true`.

There's no need to pass `-s` to install if the binaries are already stripped, which they are by default.

**Comment by nigels-com** [comment]
I do think the Debian solution is better than the Yocto one, on the face of it.
But it's already optional (STRIP=) at build-time, so better for install target to not strip?

**Comment by nigels-com** [comment]
Inclined to take both of these patches at first glance:
https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-graphics/glew/glew/no-strip.patch
https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-graphics/glew/glew/0001-Fix-build-race-in-Makefile.patch

**Comment by nigels-com** [comment]
Note: The other Yocto patch is already merged, nothing further needed there.
