### ISSUE TITLE
Linking glew

### ISSUE THREAD

**Issue by Im1Bear** [nigels-com/glew#313]
### Discussed in https://github.com/nigels-com/glew/discussions/312

<div type='discussions-op-text'>

<sup>Originally posted by **Im1Bear** August 12, 2021</sup>
I'm trying to link GLEW to my Project but every time I want to build it in Visual Studio 2019 it says that it can't open the glew32s.lib file.
</div>

**Comment by MarBg92** [comment]
Have you set the library path in the project settings for your current target and configuration?

**Comment by Im1Bear** [comment]
> Have you set the library path in the project settings for your current target and configuration?

The Problem is fixed but thanks for the Help!
