### ISSUE TITLE
GLEW Library Licensing

### ISSUE THREAD

**Issue by daniilpetrov** [nigels-com/glew#331]
Hello!

I am working on a game engine for my future game projects and am gradually getting closer to developing the first demo scene. And so I asked myself the question of licensing the libraries that I used to implement my game engine. The engine is developed exclusively for their own needs and only games made on it will be distributed. What conditions must be met in order not to violate the license to use this library?

To begin with, I indicated the use of this library in the user manual and in the future it will be so in all manuals. If you can provide a vector logo for the library, I will add it to the user manual. I also placed a copy of your license in the "documents / licenses" directory and would like to clarify if I took the correct text. If the text is different, please give the correct one.

Below I am attaching the license file and user manual for the future demo scene (one page is incomplete).
[GLEW License.txt](https://github.com/nigels-com/glew/files/7500356/GLEW.License.txt)
[manual EN.pdf](https://github.com/nigels-com/glew/files/7500357/manual.EN.pdf)

Sincerely, Daniil Petrov.

**Comment by nigels-com** [comment]
Hello Daniil,

I can speak as the current maintainer, but the licensing arrangements go back further than my involvement with GLEW.

By the sound of it you're well within the terms of the licensing.
Details are available here:

https://github.com/nigels-com/glew#copyright-and-licensing

- Nigel

**Comment by daniilpetrov** [comment]
Everything is clear, thanks!

**Comment by daniilpetrov** [comment]
On the page with logos on the texts of the titles, added hyperlinks to the sites.
[manual EN.pdf](https://github.com/nigels-com/glew/files/7511526/manual.EN.pdf)
