### ISSUE TITLE
Very simple program returns GLEW_ERROR_NO_GLX_DISPLAY

### ISSUE THREAD

**Issue by WilliamBehrens** [nigels-com/glew#332]
Here's the program:
```cpp
#include <GL/glew.h>
#include <GLFW/glfw3.h>

#include <iostream>

int main(void) {
    /* Initialize the library */
    if (!glfwInit()) { 
        return -1; 
    }
    
    /* Create a windowed mode window and its OpenGL context */
    GLFWwindow* window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    /* Initialize glew for cross-platform opengl */
    if(GLenum state = glewInit(); state != GLEW_OK) { 
        std::cerr << "Error: glewInit() returned " << state << std::endl;
        return state; 
    }

    std::cout << glGetString(GL_VERSION) << std::endl;

    /* Loop until the user closes the window */
    while (!glfwWindowShouldClose(window)) {
        /* Render here */
        glClear(GL_COLOR_BUFFER_BIT);

        /* Swap front and back buffers */
        glfwSwapBuffers(window);

        /* Poll for and process events */
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}
```
It should error on `glewInit()` and print 4, which as far as I can tell is `GLEW_ERROR_NO_GLX_DISPLAY`, I'm very new to opengl so there's a good change I've done something wrong but if it makes any difference I'm currently running this on a wayland based desktop enviroment.

**Comment by nigels-com** [comment]
Out of interest, what Linux distro and GPU and driver combo is running?

**Comment by WilliamBehrens** [comment]
Void linux and radeon 5500tx, I have the glew, glew-devel, glfw-wayland, and glfw-devel packages installed currently

**Comment by nigels-com** [comment]
GLEW can be built in EGL mode, but I don't know if they're being packaged by distros that way.

**Comment by WilliamBehrens** [comment]
What exactly is egl mode and how can I check if it's being packaged that way [here's](https://github.com/void-linux/void-packages/tree/master/srcpkgs/glew) the void package for glew

**Comment by nigels-com** [comment]
EGL is a newer alternative to GLX.
Seems like with Wayland we get X11 emulation, but not GLX.
Worth trying on your setup:
https://github.com/nigels-com/glew#linux-egl
```
LDFLAGS.GL = -lEGL -lGL
CFLAGS.EXTRA += -DGLEW_EGL
```

**Comment by WilliamBehrens** [comment]
trying with both ` g++ gl_window.cpp -lglfw -lGLEW -lGL -lGLU -lEGL -DGLEW_EGL -o gl_window` and `g++ gl_window.cpp $(pkg-config --libs --cflags glfw3 glew egl) -DGLEW_EGL -o gl_window` neither work and give the same exit code

**Comment by nigels-com** [comment]
It's the GLEW library itself that needs to be built in EGL mode.

**Comment by WilliamBehrens** [comment]
Will building with EGL remove x11 support or just adds egl? how does that all work?

**Comment by nigels-com** [comment]
Yes, it's EGL or GLX currently, but not both at the same time.
There is some interest in GLEW being able to support either or both at runtime, but it hasn't been looked at in detail.

**Comment by WilliamBehrens** [comment]
ah, understood. I'll just create an additional package in the void repos for it

**Comment by SugarRayLua** [comment]
@nigels-com, 
Would you mind providing some additional information on building glew for EGL mode?

I'm a novice linux and R user currently trying to get the following package to run under Wayland/X11:
https://github.com/tylermorganwall/shadr 
which requires GLEW in its build 

I'm on a x86_64 Ubuntu 24.04 derivative (Tuxedo-OS)
and am able to build the shadr R package find with the above instructions which recommend downloading GLEW from sourceforge.net and the R package works find under x11

However, when attempt to run the shadr R package in a Wayland environment (my preferred daily OS environment), I get the NO_GLX_DISPLAY error which I understand from this post is expected under Wayland/X11 and which can be remedied by building glew for EGL mode.

Yet, when I follow the glew github compiling instructions to 
```
make SYSTEM=linux-egl
```
Things seem to work, and glewinfo says glew2.2 is installed but I can't find where it is installed. From the shadr R package build instructions, I need to know where the glew for EGL libglew is installed and then create the symbolic link to that library that then apparently is needed during the shadr R package build. Running:
```
find -iname "*glew*"
```
doesn't reveal where the glew library is stored so presume it is not in the standard "find" search path

On the glew sourceforge.net website installation guide, it states that glew usually is installed into 
```
/usr/lib
```
which is where the shadr R package instructs me to create a symbolic link (as the download source for glew2.1 from those instructions installs glew into /usr/lib64)

Thus, I'd appreciate:
1) Any ideas as to where libglew gets installed in Ubuntu after following the make instructions for EGL mode
2) Any other suggestions you might have an optimizing the build/using glew in EGL mode for Wayland/X11

Thanks!

**Comment by nigels-com** [comment]
> make SYSTEM=linux-egl

Try following that up with `sudo make install`

Traditionally building a C/C++ code base is a separate step from installing it.  (Spraying stuff into system directories)

**Comment by SugarRayLua** [comment]
Thanks, @nigels-com, yes that worked perfectly! (It installed in the /usr/lib64 directory). I was thinking of adding that sudo make install command but wasn't sure.

Have a good night and weekend :-)

**Comment by SugarRayLua** [comment]
@nigels-com ,
Unfortunately, what I thought would be an easy solution (building in EGL mode) didn't work. 

With your suggestion, I built glew for EGL, found where it was installed, symbolically linked the library into /usr/lib (standard GLEW library that the R package shadr expects) then rebuilt and re-installed the shadr package with the new EGL mode glew library as per the github make instructions to do so. The R build showed that it successfully linked the new libGLEW2.2 built for EGL mode.

However, when I tried to use the package in R (running in RStudio IDE) with the example bouncing ball shader on the github shadr package website, the program didn't work stating it still couldn't get the GLX display. Yet, if I restart my OS in X11 (versus Wayland-X11 mode) and use that package in X11 environment, it renders the bouncing ball shader just fine.

Are their limitations on what the EGL mode build can do (for some won't work with the shadr package or R)?

If you are interested and have time in the future it would be great to see if you might be able to figure out why the glew build for EGL won't work for the shadr R package running in a Wayland environment. (It's a neat package-- not only can you create shaders in the R environment but the package also lets you export the shaders you create as .mpeg or .gifs which are nice to share with others).

Thanks again :-)

**Comment by nigels-com** [comment]
I don't have familiarity with R, but in my line of work it would be of interest to have some hands on with it.

There is a broader question here for GLEW concerning this X11 vs Wayland/EGL situation on the Linux desktop.
I had sort of hoped this would have been sorted out by others, but kind of issue pops up here from time to time.
I'm personally a solid X11/Nvidia traditionalist for quite a long time, but I guess EGL is here to stay.

- Nigel
