### ISSUE TITLE
glewInit failed: Missing GL version

### ISSUE THREAD

**Issue by VladimirBessonov** [nigels-com/glew#344]
the code below works fine on windows, but returns glewInit failed: Missing GL version on macos. 
Please advise
`

#include <glew.h>
#include <glfw3.h>
#include <iostream>
using namespace std;

void init(GLFWwindow* window) { }
void display(GLFWwindow* window, double currentTime) {
glClearColor(1.0, 0.0, 0.0, 1.0);
glClear(GL_COLOR_BUFFER_BIT);
}
int main(void) {
if (!glfwInit()) { exit(EXIT_FAILURE); }
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
GLFWwindow* window = glfwCreateWindow(600, 600, "Chapter2 - program1", NULL, NULL);
glfwMakeContextCurrent(window);
glewExperimental = GL_TRUE;
    
if (glewInit() != GLEW_OK) {
    GLenum err=glewInit();
    cout << "glewInit failed: " << glewGetErrorString(err) << endl;
    exit(EXIT_FAILURE); }
glfwSwapInterval(1);
init(window);
while (!glfwWindowShouldClose(window)) {
display(window, glfwGetTime());
glfwSwapBuffers(window);
glfwPollEvents();
}
glfwDestroyWindow(window);
glfwTerminate();
exit(EXIT_SUCCESS);
}

`

**Comment by nigels-com** [comment]
Are you sure you have an OpenGL context?
Would be worth checking.

**Comment by VladimirBessonov** [comment]
if it is running in visual studio, could it be there there is no OpenGL context? 
Is it a bot that replies?

**Comment by nigels-com** [comment]
See: https://www.glfw.org/faq.html#41---how-do-i-create-an-opengl-30-context

I'm not sure that 4.2 context is available on macos.
