### ISSUE TITLE
My program won't run on Windows 7 with Glew

### ISSUE THREAD

**Issue by photowen** [nigels-com/glew#347]
Development platform VS2008 + Win10，
tip:The procedure entry point wcscat_s could not be locating in the dynamic link library msvcrt.dll

**Comment by nigels-com** [comment]
For VS2008 you'll likely need to build the glew.dll to depend on older C runtime API.

**Comment by photowen** [comment]
I found out that it was a problem with the version of opengl, delete the dll in my program, link the opengl that comes with xp by default, and the program runs normally. But it doesn't render properly.
