### ISSUE TITLE
LNK Errors

### ISSUE THREAD

**Issue by Avocadobeef** [nigels-com/glew#353]
Hi,
I am working on QT ( with MSVC2017 64bit Kit) and CMAKE and i am trying to include the glew library into my project. I am new to CMAKE and I feel like I am linking the wrong .lib files or .dll files or missing a step. I tried compiling the glew_shared and glew_static folder in VSC2017 and adding the glew32d.dll and glew32ds.lib to sub folder and linking them to my project, but I am still getting the same error. 

Any idea what I could or should be doing differently?

Here the Error Message:
![Error_Messages](https://user-images.githubusercontent.com/72135329/152976300-660a2f2b-48b9-452f-9fc1-47c4b0e563c1.png)
 
Cheers

**Comment by nigels-com** [comment]
glew32ds.lib for Debug-mode and glew32s.lib for Release-mode ought to work.

- Nigel

**Comment by Avocadobeef** [comment]
Well I am in Debug-mode and linked the glew32sd.lib, so I guess the error might be somewhere else.

Cheers,
Marco

**Comment by nigels-com** [comment]
Keep in mind that the other way to use GLEW is to simply compile it in.  (In GLEW_STATIC mode)

**Comment by Avocadobeef** [comment]
What do you mean by compile it in? 
I tried a new approach, i used CMAKE to build and generate the library (from the CMAKE folder in the code). Built it with MSCV2017 (BUILD ALL and INSTALL). And now i can use the find_package() command to find glew. 
I thought doing it this might resolve link problems, the error I now have is it doesn't find 'GL/glew.h'.
