### ISSUE TITLE
GL_NVX_progress_fence missing glCreateProgressFenceNVX

### ISSUE THREAD

**Issue by Gpinchon** [nigels-com/glew#355]
[According to the registery](https://www.khronos.org/registry/OpenGL/extensions/NVX/NVX_progress_fence.txt)

> The commands **SignalSemaphoreui64NVX**, **WaitSemaphoreui64NVX** and 
> **ClientWaitSemaphoreui64NVX** accept semaphore object names as input in 
> <semaphoreArray> that were created by **CreateProgressFenceNVX** or imported
> from a handle of the type HANDLE_TYPE_D3D12_FENCE_EXT. 
> If a value in <semaphoreArray> is not the name of such a semaphore object, 
> an INVALID_VALUE error is generated.

Function could maybe be replaced with glGenSemaphoresEXT, but it seems unsure according to the specs. If I'm not mistaken, this extension is incomplete anyway.

**Comment by nigels-com** [comment]
Hello, indeed you've hit a bug in the crufty old perl scripts.
I made a fix, uploaded a snapshot:
https://sourceforge.net/projects/glew/files/glew/snapshots/glew-20220402.tgz/download

Regards.
