### ISSUE TITLE
Seeking clarity on canonical releases

### ISSUE THREAD

**Issue by ncook-hxgn** [nigels-com/glew#359]
Hi there

Where is the Official™ place to get new releases of GLEW binaries?

If it's here, awesome. (Any chance of a nuget package? Currently I'm building my own. Happy to make a PR if you like?)

The Sourceforge website seems to be out of date/behind Github: the latest release here is 2.2.0, and the latest listed on the sourceforge page is 2.1.0.

**Comment by nigels-com** [comment]
Yes, this is the right place.

**Comment by nigels-com** [comment]
That's a good point that it's time to update the HTML to point to the markdown.

**Comment by ncook-hxgn** [comment]
Thanks :)
