### ISSUE TITLE
Can't find GL/glew.h in Xcode project after make install 

### ISSUE THREAD

**Issue by Edwinzero** [nigels-com/glew#36]
I am using Xcode6.2 and OSX 10.10, I try almost all the instructions of glew configuration on the internet and it turns out that compiler keep telling me that can't find glew.h
Is there any solutions ?

**Comment by nigels-com** [comment]
Did the glew.h get installed to /usr/local/include/GL ?  Try -I/usr/local/include flag.

**Comment by Edwinzero** [comment]
It works!!!! Thank you very much!!!! You are awesome!

**Comment by nigels-com** [comment]
No worries.
