### ISSUE TITLE
Used Glew on Wayland Weston (Opengles only) and got some errors

### ISSUE THREAD

**Issue by zack-huangzihan** [nigels-com/glew#362]
I used Glew on Wayland Weston (Opengles only) and got some errors:

Starting GLFW context, OpenGL 3.3
arm_release_ver of this libmali is 'g6p0-01eac0', rk_so_ver is '5'.
Error: Wayland: Focusing a window requires user interaction
Error: Wayland: Standard cursor not found
Error: Wayland: Standard cursor not found
Error: Wayland: Standard cursor not found
Error: Wayland: Standard cursor not found

I don't know if it will affect anything, who knows how to deal with it?

**Comment by nigels-com** [comment]
These errors don't (on the face of it) look like a problem with GLEW.

**Comment by zack-huangzihan** [comment]
ok
