### ISSUE TITLE
NamedBufferPageCommitmentARB is missing

### ISSUE THREAD

**Issue by Groovounet** [nigels-com/glew#37]
https://www.opengl.org/registry/specs/ARB/sparse_buffer.txt defines NamedBufferPageCommitmentARB as an intersection with ARB_dsa extension but the function is not defined in GLEW 1.12.

Thanks,
Christophe

**Comment by nigels-com** [comment]
I see. These multi-extension scenarios are awkward for GLEW.  Thanks for the heads-up.

**Comment by Groovounet** [comment]
There were an interaction planed with https://www.opengl.org/registry/specs/ARB/sparse_texture.txt to expose glTexturePageCommitmentARB if ARB_dsa but it seems the spec never got updated or actually the update never got published.
