### ISSUE TITLE
GLsizeiptr is supposed to be unsigned

### ISSUE THREAD

**Issue by dukeeeey** [nigels-com/glew#373]
On windows

typedef ptrdiff_t GLintptr;
typedef ptrdiff_t GLsizeiptr;

Both are signed

#ifdef _WIN64
    typedef unsigned __int64 size_t;
    typedef __int64          ptrdiff_t;
    typedef __int64          intptr_t;
#else
    typedef unsigned int     size_t;
    typedef int              ptrdiff_t;
    typedef int              intptr_t;
#endif

**Comment by nigels-com** [comment]
However, it signed in [glcorearb.h](https://registry.khronos.org/OpenGL/api/GL/glcorearb.h)

```
#ifndef GL_VERSION_1_5
#define GL_VERSION_1_5 1
typedef khronos_ssize_t GLsizeiptr;
typedef khronos_intptr_t GLintptr;
```

**Comment by dukeeeey** [comment]
Yeah strange, guess i'll close this then.
