### ISSUE TITLE
Am I hallucinating or is there no include folder in the repo?

### ISSUE THREAD

**Issue by Sedomanai** [nigels-com/glew#382]
Sorry for the cheeky title but I genuinely have no idea what's going on.
I'm using cmake and I tried to install using the CMakeLists.txt in the build/cmake folder, 
but these directories simply don't exist:
  ${GLEW_DIR}/include/GL/wglew.h
  ${GLEW_DIR}/include/GL/glew.h
  ${GLEW_DIR}/include/GL/glxew.h
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/GL)

${GLEW_DIR} being the root of this project, I assume. 
In any case I can't find any include folder in the repo.

I tried finding the glew package directly from glew-config.cmake, 
but then there's no glew-targets.cmake?....

in glew-config.cmake: 
  ...
  include(${CMAKE_CURRENT_LIST_DIR}/glew-targets.cmake)
  include(${CMAKE_CURRENT_LIST_DIR}/CopyImportedTargetProperties.cmake)
  ...

I don't know what's going on, I searched everywhere on how to use cmake to install glew 
but all the questions and docs already assumes you installed it, or it is already installed by default, or something.

Am I missing something?

**Comment by Sedomanai** [comment]
I actually understand the process now. Apparently the source files are generated via make, which I don't use. I also found the Perlmint forked repo so everything's good. Sorry, I was lost for a sec there. However, it'd be nice if there's a signpost pointing me to the right direction, for those using cmake without make.

**Comment by nigels-com** [comment]
I'd be happy to remove the cmake projects, but some people need them, presumably.
It's not useful for _maintaining_ GLEW, unfortunately.
