### ISSUE TITLE
Isn’t `dllimport` obsolete?

### ISSUE THREAD

**Issue by JakeSmarter** [nigels-com/glew#385]
https://github.com/nigels-com/glew/blob/ef7d12ecb7f1f336f6d3a80cebd6163b2c094108/auto/src/glew_head.h#L118-L126

~~and has only applied to ancient versions of Cygwin, maybe also ancient MinGW32 but never to MSVC or ICC.~~ Binutil’s `ld` is capable of linking to import libs and DLLs with or without the [`__imp_` symbol prefix since August 2<sup>nd</sup>, 2001](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=8ceb7a1b8e7893e3859433dd99174055a6d47aad)! Please, remove the use of `dllimport` from the headers. It causes more harm and confusion then good. If someone really wants to prefix GLEW’s symbols with `__imp_` then they can configure their compiler or linker to do so, though I doubt anybody would want this. Hence, there is also no need for the `GLEW_STATIC` macro to exist.

**Comment by nigels-com** [comment]
Is there a specific issue you're having?

The binary API is essentially frozen, there would a lot of reluctance to change this.

**Comment by nigels-com** [comment]
My perception of `dllimport` is that it's rather more conventional than being a "relic of Cygwin".  But I do follow your reasoning and think it has technical merit.  The practical problem is that if I get this wrong and widespread breakage results, I will likely get flooded with nasty outrage, the internet being how it is.  I don't think using and requiring GLEW_STATIC is such a burden, but I admit that I just expect Windows development to be needlessly "annoying" like this.

**Comment by nigels-com** [comment]
I guess one thing for me to revise is the implications of having the `__imp_` prefix, or not.  I do regard that as an ABI change, but what is the risk of that change more broadly?

**Comment by nigels-com** [comment]
https://learn.microsoft.com/en-us/cpp/build/importing-into-an-application-using-declspec-dllimport?view=msvc-170

> Using __declspec(dllimport) is optional on function declarations, but the compiler produces more
> efficient code if you use this keyword. However, you must use __declspec(dllimport) for the importing
> executable to access the DLL's public data symbols and objects. Note that the users of your DLL still
> need to link with an import library.

**Comment by nigels-com** [comment]
> the compiler generates slightly different code when it needs to reference an imported function, since the compiler is aware of the special way imported functions are implemented.

https://devblogs.microsoft.com/oldnewthing/20060724-00/?p=30403

> If you forget to declare a function as dllimport, then you’re basically making the compiler act like a naive compiler that doesn’t understand dllimport. When the linker goes to resolve the external reference for the function, it will use the stub from the import library, and everything will work as before. You do miss out on the optimization that dllimport enables, but the code will still run. You’re just running in naive mode.

https://devblogs.microsoft.com/oldnewthing/20060726-00/?p=30363

> The fact that names in import libraries are decorated means that it is doubly crucial that you use the official import library for the DLL you wish to use rather than trying to manufacture one with an import library generation tool. As we noted earlier, the tool won’t know whether the ordinal assigned to a named function was by design or merely coincidental.

https://devblogs.microsoft.com/oldnewthing/20060727-00/?p=30343

**Comment by nigels-com** [comment]
I'm sincere in saying that I didn't intend to tour this particular rabbit-hole, but a bit glad to have had a look and a conversation.

So far I'm leaning towards status-quo.  Some reasoning:

1. It still seems to be what Microsoft recommends as best-practice.
2. GLEW is a C library intended for maximum portability, including obsolete compilers.
3. There isn't much reward (for me) in making a change, but risk of breakage, and resulting maintainer grief.
4. GLEW has been around a long time, has accumulated a fairly large install-base, I think that stability is generally valued.
5. I don't happen to have old MS compilers to test with, and not motivated to go above and beyond to test for real.
6. It's irritating to deal with the import/export/static macro stuff, but it's nothing new or unique to GLEW.
7. Considering it's still required for data exports, doesn't seem unreasonable to be consistent.
