### ISSUE TITLE
Change CMake min version

### ISSUE THREAD

**Issue by Sororfortuna** [nigels-com/glew#388]
on latest CMake release (3.27)
```
glew/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
[cmake]   CMake.
[cmake] 
[cmake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
[cmake]   CMake that the project does not need compatibility with older versions.
```

**Comment by nigels-com** [comment]
https://cmake.org/cmake/help/latest/release/3.27.html#deprecated-and-removed-features

**Comment by grahamreeds** [comment]
Does the project rely on anything which is being deprecated/removed?

Also I wouldn't recommend advancing to 3.27 as Debian 11 is on 3.18 and not everyone can upgrade to the latest and greatest.  
What we do is to pick the version of what the oldest LTS Ubuntu is using and make that the minimum.

**Comment by Sororfortuna** [comment]
> Does the project rely on anything which is being deprecated/removed?
> 
> Also I wouldn't recommend advancing to 3.27 as Debian 11 is on 3.18 and not everyone can upgrade to the latest and greatest. What we do is to pick the version of what the oldest LTS Ubuntu is using and make that the minimum.
> 
> EDIT: Bumped the version to 3.16 which is what Ubuntu LTS is using (https://launchpad.net/ubuntu/focal/+source/cmake). However there are more serious issues as I can't get the Makefile or the CMake version to build the library (#392).

Advancing to 3.27 is probably overkill, I believe VS2022 has 3.26 but I guess 3.16 should do the trick.

**Comment by nigels-com** [comment]
Merged and done.  Thanks all.
