### ISSUE TITLE
Error building glew-1.12.0 on Windows 7

### ISSUE THREAD

**Issue by TimothyWrightSoftware** [nigels-com/glew#39]
Here is the output from the CMake configure:

The C compiler identification is MSVC 18.0.31101.0
The CXX compiler identification is MSVC 18.0.31101.0
Check for working C compiler using: Visual Studio 12 2013 Win64
Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 12 2013 Win64
Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.0/Modules/FindPkgConfig.cmake:381 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)

Configuring incomplete, errors occurred!
See also "C:/game_dev/3rd/glew-1.12.0/cmake-build/CMakeFiles/CMakeOutput.log".

**Comment by nigels-com** [comment]
I'd suggest using the provided solutions, as an alternative.
Cmake support is new, I don't think it ought to be depending on PkgConfig for a Windows build.
Hopefully someone with Windows can take a look at this.  I don't have Windows at the moment.

**Comment by TimothyWrightSoftware** [comment]
It's not a big deal.  The binaries work fine.  I just wanted to let you guys know.  I commented that part out of the cmake file and tried to build it anyway, but didn't have any luck.  If I figure anything I will let you guys know or send a pull request.

**Comment by nigels-com** [comment]
I'm considering having a Windows laptop, or perhaps a VM.  But right at the moment there isn't much I can do to help on this one.

**Comment by BastiaanOlij** [comment]
I'll have a look when I'm home tonight what my Windows 7 machine at home does. I'm on an older version of VC though so not sure how much help that will be.

**Comment by oldmud0** [comment]
This is driving me nuts.

**Comment by TimothyWrightSoftware** [comment]
If you need me to try again or send more info, just let me know.  I spend most days fighting with weird bugs in our JIRA system, so I understand.  :-)

**Comment by wguo68** [comment]
I also have the same compile error

**Comment by zhangzhensong** [comment]
The same problem.
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at D:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindPkgConfig.cmake:388 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  D:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)

**Comment by nigels-com** [comment]
Ant Windows cmake users that can propose a patch for this?

**Comment by Fredericvo** [comment]
I desperately need this too. The provided binary is linked to an incompatible platform toolset.
I need msvcrt & msvcrtd /MDd vs120 build.

**Comment by nigels-com** [comment]
cmake build is still experimental.

The included MSVC solutions still work, right?

- Nigel

**Comment by Fredericvo** [comment]
Yes, it did. :-) Maybe cmake would've worked too if I hadn't forgotten that what I had downloaded first a few days ago was just the binary zip package but since the msvc solution worked I didn't actually retry cmake on the second download.
Anyway, consider my previous post null and void.

**Comment by tamaskenez** [comment]
This issue has been fixed since 1.12.0, it's on the master now.
It has been fixed by xantares's cmake rewrite (40513e0bb46)

**Comment by nigels-com** [comment]
Works for me too, closing.

**Comment by Xirema** [comment]
I downloaded the most recent version of the GLEW source available on the website, and I'm getting the same CMake error as the original poster:

The C compiler identification is MSVC 18.0.31101.0
The CXX compiler identification is MSVC 18.0.31101.0
Check for working C compiler using: Visual Studio 12 2013 Win64
Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 12 2013 Win64
Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPkgConfig.cmake:388 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)


Configuring incomplete, errors occurred!
See also "C:/Users/admin/VCworkspace/Compiled-GLEW/CMakeFiles/CMakeOutput.log".

Is pkg-config still supposed to be part of the cmake list?

**Comment by nigels-com** [comment]
Yeah, I think it's time for a fresh snapshot on source forge. I tried uploading one yesterday, I'll give it another try.

**Comment by nigels-com** [comment]
There is a new snapshot available, which ought to work.
http://sourceforge.net/projects/glew/files/glew/snapshots/glew-20150805.tgz/download
