### ISSUE TITLE
The problem encountered when compiling with CMake on Windows

### ISSUE THREAD

**Issue by wk34u** [nigels-com/glew#408]
The code from the master branch lacks some files when compiling with CMake on Windows.

The files missing are:

    glew\include\GL\glxew.h
    glew\include\GL\glew.h
    glew\include\GL\wglew.h
    glew\include\GL\eglew.h

However, these files are available in the following locations:
![glew-2.2.0 release on GitHub](https://github.com/nigels-com/glew/releases/tag/glew-2.2.0)
![glew-2.2.0 release on SourceForge](https://sourceforge.net/projects/glew/files/glew/2.2.0/glew-2.2.0.zip)

The CMake commands used are as follows:

```bash
cd glew
cmake ./build/cmake
cmake --build ./
```

**Comment by nigels-com** [comment]
The generated sources are not included in the git repository due to their size and gradual drift.
