### ISSUE TITLE
Compilation Error: 

### ISSUE THREAD

**Issue by PedroVMota** [nigels-com/glew#412]
➜  glew git:(master) ✗ make
mkdir lib
make: *** No rule to make target `src/glew.c', needed by `tmp/darwin/default/shared/glew.o'.  Stop.

➜  build git:(master) ✗ cmake ./cmake
-- Configuring done (0.0s)
CMake Error at CMakeLists.txt:114 (add_library):
  Cannot find source file:

    /Users/pedro/Desktop/Projects/OpenGl/Dependencies/glew/include/GL/wglew.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
  
  

CMake Error at CMakeLists.txt:185 (add_executable):
  Cannot find source file:

    /Users/pedro/Desktop/Projects/OpenGl/Dependencies/glew/src/glewinfo.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:114 (add_library):
  No SOURCES given to target: glew

CMake Error at CMakeLists.txt:118 (add_library):
  No SOURCES given to target: glew_s

CMake Error at CMakeLists.txt:185 (add_executable):
  No SOURCES given to target: glewinfo

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by nigels-com** [comment]
See Issue #13
