### ISSUE TITLE
(Question) What backends does GLEW support?

### ISSUE THREAD

**Issue by hardBSDk** [nigels-com/glew#413]
GLEW seems to have a dependency on X11, but is it mandatory?

**Comment by nigels-com** [comment]
There is also EGL mode, if I recall correctly.
https://github.com/nigels-com/glew/blob/master/config/Makefile.linux-egl

**Comment by hardBSDk** [comment]
@nigels-com Thanks for the answer!

**Comment by hardBSDk** [comment]
@nigels-com I saw a GNU Make flag to build GLEW for OSMesa, this is what I wanted.
