### ISSUE TITLE
glew.c compilation failed

### ISSUE THREAD

**Issue by ShohjahonOktamov** [nigels-com/glew#415]
I needed "libglew32s.a" to link statically, but I could not find and decided to make it myself. I compiled "glew.c" file from "src/" folder:

$ g++ -Wall -O2 -o glew.0 -c glew.c

glew.c: In function 'GLboolean _glewStrSame1(const GLubyte**, GLuint*, const GLubyte*, GLuint)':
glew.c:244:29: warning: comparing the result of pointer addition '((* a) + ((sizetype)i))' and NULL
[-Waddress]
  244 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                             ^
glew.c:244:44: warning: comparing the result of pointer addition '(b + ((sizetype)i))' and NULL [-Wa
ddress]
  244 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                                            ^
glew.c: In function 'GLboolean _glewStrSame2(const GLubyte**, GLuint*, const GLubyte*, GLuint)':
glew.c:260:29: warning: comparing the result of pointer addition '((* a) + ((sizetype)i))' and NULL
[-Waddress]
  260 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                             ^
glew.c:260:44: warning: comparing the result of pointer addition '(b + ((sizetype)i))' and NULL [-Wa
ddress]
  260 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                                            ^
glew.c: In function 'GLboolean _glewStrSame3(const GLubyte**, GLuint*, const GLubyte*, GLuint)':
glew.c:276:29: warning: comparing the result of pointer addition '((* a) + ((sizetype)i))' and NULL
[-Waddress]
  276 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                             ^
glew.c:276:44: warning: comparing the result of pointer addition '(b + ((sizetype)i))' and NULL [-Wa
ddress]
  276 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                                            ^
glew.c: At global scope:
glew.c:311:28: warning: '__glewCopyTexSubImage3D' redeclared without dllimport attribute: previous d
llimport ignored [-Wattributes]
  311 | PFNGLCOPYTEXSUBIMAGE3DPROC __glewCopyTexSubImage3D = NULL;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
glew.c:312:28: warning: '__glewDrawRangeElements' redeclared without dllimport attribute: previous d
llimport ignored [-Wattributes]
  312 | PFNGLDRAWRANGEELEMENTSPROC __glewDrawRangeElements = NULL;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
glew.c:313:21: warning: '__glewTexImage3D' redeclared without dllimport attribute: previous dllimpor
t ignored [-Wattributes]
  313 | PFNGLTEXIMAGE3DPROC __glewTexImage3D = NULL;
      |                     ^~~~~~~~~~~~~~~~
glew.c:314:24: warning: '__glewTexSubImage3D' redeclared without dllimport attribute: previous dllim
port ignored [-Wattributes]
  314 | PFNGLTEXSUBIMAGE3DPROC __glewTexSubImage3D = NULL;
      |                        ^~~~~~~~~~~~~~~~~~~
glew.c:316:24: warning: '__glewActiveTexture' redeclared without dllimport attribute: previous dllim
port ignored [-Wattributes]
  316 | PFNGLACTIVETEXTUREPROC __glewActiveTexture = NULL;
      |                        ^~~~~~~~~~~~~~~~~~~
glew.c:317:30: warning: '__glewClientActiveTexture' redeclared without dllimport attribute: previous
 dllimport ignored [-Wattributes]
  317 | PFNGLCLIENTACTIVETEXTUREPROC __glewClientActiveTexture = NULL;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:318:31: warning: '__glewCompressedTexImage1D' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
  318 | PFNGLCOMPRESSEDTEXIMAGE1DPROC __glewCompressedTexImage1D = NULL;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:319:31: warning: '__glewCompressedTexImage2D' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
  319 | PFNGLCOMPRESSEDTEXIMAGE2DPROC __glewCompressedTexImage2D = NULL;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:320:31: warning: '__glewCompressedTexImage3D' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
  320 | PFNGLCOMPRESSEDTEXIMAGE3DPROC __glewCompressedTexImage3D = NULL;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:321:34: warning: '__glewCompressedTexSubImage1D' redeclared without dllimport attribute: prev
ious dllimport ignored [-Wattributes]
  321 | PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC __glewCompressedTexSubImage1D = NULL;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:322:34: warning: '__glewCompressedTexSubImage2D' redeclared without dllimport attribute: prev
ious dllimport ignored [-Wattributes]
  322 | PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC __glewCompressedTexSubImage2D = NULL;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:323:34: warning: '__glewCompressedTexSubImage3D' redeclared without dllimport attribute: prev
ious dllimport ignored [-Wattributes]
  323 | PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC __glewCompressedTexSubImage3D = NULL;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:324:32: warning: '__glewGetCompressedTexImage' redeclared without dllimport attribute: previo
us dllimport ignored [-Wattributes]
  324 | PFNGLGETCOMPRESSEDTEXIMAGEPROC __glewGetCompressedTexImage = NULL;
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:325:31: warning: '__glewLoadTransposeMatrixd' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
  325 | PFNGLLOADTRANSPOSEMATRIXDPROC __glewLoadTransposeMatrixd = NULL;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:326:31: warning: '__glewLoadTransposeMatrixf' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
  326 | PFNGLLOADTRANSPOSEMATRIXFPROC __glewLoadTransposeMatrixf = NULL;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:327:31: warning: '__glewMultTransposeMatrixd' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
  327 | PFNGLMULTTRANSPOSEMATRIXDPROC __glewMultTransposeMatrixd = NULL;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:328:31: warning: '__glewMultTransposeMatrixf' redeclared without dllimport attribute: previou
s dllimport ignored [-Wattributes]
  328 | PFNGLMULTTRANSPOSEMATRIXFPROC __glewMultTransposeMatrixf = NULL;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
glew.c:329:26: warning: '__glewMultiTexCoord1d' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  329 | PFNGLMULTITEXCOORD1DPROC __glewMultiTexCoord1d = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:330:27: warning: '__glewMultiTexCoord1dv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  330 | PFNGLMULTITEXCOORD1DVPROC __glewMultiTexCoord1dv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:331:26: warning: '__glewMultiTexCoord1f' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  331 | PFNGLMULTITEXCOORD1FPROC __glewMultiTexCoord1f = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:332:27: warning: '__glewMultiTexCoord1fv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  332 | PFNGLMULTITEXCOORD1FVPROC __glewMultiTexCoord1fv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:333:26: warning: '__glewMultiTexCoord1i' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  333 | PFNGLMULTITEXCOORD1IPROC __glewMultiTexCoord1i = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:334:27: warning: '__glewMultiTexCoord1iv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  334 | PFNGLMULTITEXCOORD1IVPROC __glewMultiTexCoord1iv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:335:26: warning: '__glewMultiTexCoord1s' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  335 | PFNGLMULTITEXCOORD1SPROC __glewMultiTexCoord1s = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:336:27: warning: '__glewMultiTexCoord1sv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  336 | PFNGLMULTITEXCOORD1SVPROC __glewMultiTexCoord1sv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:337:26: warning: '__glewMultiTexCoord2d' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  337 | PFNGLMULTITEXCOORD2DPROC __glewMultiTexCoord2d = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:338:27: warning: '__glewMultiTexCoord2dv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  338 | PFNGLMULTITEXCOORD2DVPROC __glewMultiTexCoord2dv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:339:26: warning: '__glewMultiTexCoord2f' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  339 | PFNGLMULTITEXCOORD2FPROC __glewMultiTexCoord2f = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:340:27: warning: '__glewMultiTexCoord2fv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  340 | PFNGLMULTITEXCOORD2FVPROC __glewMultiTexCoord2fv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:341:26: warning: '__glewMultiTexCoord2i' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  341 | PFNGLMULTITEXCOORD2IPROC __glewMultiTexCoord2i = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:342:27: warning: '__glewMultiTexCoord2iv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  342 | PFNGLMULTITEXCOORD2IVPROC __glewMultiTexCoord2iv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:343:26: warning: '__glewMultiTexCoord2s' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  343 | PFNGLMULTITEXCOORD2SPROC __glewMultiTexCoord2s = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:344:27: warning: '__glewMultiTexCoord2sv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  344 | PFNGLMULTITEXCOORD2SVPROC __glewMultiTexCoord2sv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:345:26: warning: '__glewMultiTexCoord3d' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  345 | PFNGLMULTITEXCOORD3DPROC __glewMultiTexCoord3d = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:346:27: warning: '__glewMultiTexCoord3dv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  346 | PFNGLMULTITEXCOORD3DVPROC __glewMultiTexCoord3dv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:347:26: warning: '__glewMultiTexCoord3f' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  347 | PFNGLMULTITEXCOORD3FPROC __glewMultiTexCoord3f = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:348:27: warning: '__glewMultiTexCoord3fv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  348 | PFNGLMULTITEXCOORD3FVPROC __glewMultiTexCoord3fv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:349:26: warning: '__glewMultiTexCoord3i' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  349 | PFNGLMULTITEXCOORD3IPROC __glewMultiTexCoord3i = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:350:27: warning: '__glewMultiTexCoord3iv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  350 | PFNGLMULTITEXCOORD3IVPROC __glewMultiTexCoord3iv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:351:26: warning: '__glewMultiTexCoord3s' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  351 | PFNGLMULTITEXCOORD3SPROC __glewMultiTexCoord3s = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:352:27: warning: '__glewMultiTexCoord3sv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  352 | PFNGLMULTITEXCOORD3SVPROC __glewMultiTexCoord3sv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:353:26: warning: '__glewMultiTexCoord4d' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  353 | PFNGLMULTITEXCOORD4DPROC __glewMultiTexCoord4d = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:354:27: warning: '__glewMultiTexCoord4dv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  354 | PFNGLMULTITEXCOORD4DVPROC __glewMultiTexCoord4dv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:355:26: warning: '__glewMultiTexCoord4f' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  355 | PFNGLMULTITEXCOORD4FPROC __glewMultiTexCoord4f = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:356:27: warning: '__glewMultiTexCoord4fv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  356 | PFNGLMULTITEXCOORD4FVPROC __glewMultiTexCoord4fv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:357:26: warning: '__glewMultiTexCoord4i' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  357 | PFNGLMULTITEXCOORD4IPROC __glewMultiTexCoord4i = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:358:27: warning: '__glewMultiTexCoord4iv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  358 | PFNGLMULTITEXCOORD4IVPROC __glewMultiTexCoord4iv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:359:26: warning: '__glewMultiTexCoord4s' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  359 | PFNGLMULTITEXCOORD4SPROC __glewMultiTexCoord4s = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:360:27: warning: '__glewMultiTexCoord4sv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  360 | PFNGLMULTITEXCOORD4SVPROC __glewMultiTexCoord4sv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:361:25: warning: '__glewSampleCoverage' redeclared without dllimport attribute: previous dlli
mport ignored [-Wattributes]
  361 | PFNGLSAMPLECOVERAGEPROC __glewSampleCoverage = NULL;
      |                         ^~~~~~~~~~~~~~~~~~~~
glew.c:363:21: warning: '__glewBlendColor' redeclared without dllimport attribute: previous dllimpor
t ignored [-Wattributes]
  363 | PFNGLBLENDCOLORPROC __glewBlendColor = NULL;
      |                     ^~~~~~~~~~~~~~~~
glew.c:364:24: warning: '__glewBlendEquation' redeclared without dllimport attribute: previous dllim
port ignored [-Wattributes]
  364 | PFNGLBLENDEQUATIONPROC __glewBlendEquation = NULL;
      |                        ^~~~~~~~~~~~~~~~~~~
glew.c:365:28: warning: '__glewBlendFuncSeparate' redeclared without dllimport attribute: previous d
llimport ignored [-Wattributes]
  365 | PFNGLBLENDFUNCSEPARATEPROC __glewBlendFuncSeparate = NULL;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
glew.c:366:26: warning: '__glewFogCoordPointer' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  366 | PFNGLFOGCOORDPOINTERPROC __glewFogCoordPointer = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:367:20: warning: '__glewFogCoordd' redeclared without dllimport attribute: previous dllimport
 ignored [-Wattributes]
  367 | PFNGLFOGCOORDDPROC __glewFogCoordd = NULL;
      |                    ^~~~~~~~~~~~~~~
glew.c:368:21: warning: '__glewFogCoorddv' redeclared without dllimport attribute: previous dllimpor
t ignored [-Wattributes]
  368 | PFNGLFOGCOORDDVPROC __glewFogCoorddv = NULL;
      |                     ^~~~~~~~~~~~~~~~
glew.c:369:20: warning: '__glewFogCoordf' redeclared without dllimport attribute: previous dllimport
 ignored [-Wattributes]
  369 | PFNGLFOGCOORDFPROC __glewFogCoordf = NULL;
      |                    ^~~~~~~~~~~~~~~
glew.c:370:21: warning: '__glewFogCoordfv' redeclared without dllimport attribute: previous dllimpor
t ignored [-Wattributes]
  370 | PFNGLFOGCOORDFVPROC __glewFogCoordfv = NULL;
      |                     ^~~~~~~~~~~~~~~~
glew.c:371:26: warning: '__glewMultiDrawArrays' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  371 | PFNGLMULTIDRAWARRAYSPROC __glewMultiDrawArrays = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:372:28: warning: '__glewMultiDrawElements' redeclared without dllimport attribute: previous d
llimport ignored [-Wattributes]
  372 | PFNGLMULTIDRAWELEMENTSPROC __glewMultiDrawElements = NULL;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
glew.c:373:26: warning: '__glewPointParameterf' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  373 | PFNGLPOINTPARAMETERFPROC __glewPointParameterf = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:374:27: warning: '__glewPointParameterfv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  374 | PFNGLPOINTPARAMETERFVPROC __glewPointParameterfv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:375:26: warning: '__glewPointParameteri' redeclared without dllimport attribute: previous dll
import ignored [-Wattributes]
  375 | PFNGLPOINTPARAMETERIPROC __glewPointParameteri = NULL;
      |                          ^~~~~~~~~~~~~~~~~~~~~
glew.c:376:27: warning: '__glewPointParameteriv' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  376 | PFNGLPOINTPARAMETERIVPROC __glewPointParameteriv = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:377:27: warning: '__glewSecondaryColor3b' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  377 | PFNGLSECONDARYCOLOR3BPROC __glewSecondaryColor3b = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:378:28: warning: '__glewSecondaryColor3bv' redeclared without dllimport attribute: previous d
llimport ignored [-Wattributes]
  378 | PFNGLSECONDARYCOLOR3BVPROC __glewSecondaryColor3bv = NULL;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
glew.c:379:27: warning: '__glewSecondaryColor3d' redeclared without dllimport attribute: previous dl
limport ignored [-Wattributes]
  379 | PFNGLSECONDARYCOLOR3DPROC __glewSecondaryColor3d = NULL;
      |                           ^~~~~~~~~~~~~~~~~~~~~~
glew.c:380:28: warning: '__glewSecondaryColor3dv' redeclared without dllimport attribute: previous d
llimport ignored [-Wattributes]
  380 | PFNGLSECONDARYCOLOR3DVPROC __glewSecondaryColor3dv = NULL;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~

I got errors and warnings (I had more warnings, but I can't fit them there)

I am using Windows 10 x64, MSYS2 and "mingw-w64-x86_64-gcc-14.1.0-3"
I have tried to compile glew 2.0.0, 2.1.0 and 2.2.0 versions

It will be compiled but when including it and using it leads to undefined reference errors. However, it worked just fine when I used dynamic "libglew32.a"

I need the way to fix this or "libglew32s.a" file (I have tried to rename "libglew32.a" to "liblgew32s.a", but it also caused the same errors)

**Comment by nigels-com** [comment]
Compiling with `-DGLEW_STATIC` should resolve the dll import warnings.

**Comment by ShohjahonOktamov** [comment]
> Compiling with `-DGLEW_STATIC` should resolve the dll import warnings.

I tried including -DGLEW_STATIC flag and defining it in code, it did not help

**Comment by nigels-com** [comment]
Still getting warnings, but still getting errors?  (Just omit -Wall to make the warnings go away?)

**Comment by ShohjahonOktamov** [comment]
I have already tried this, but after making glew.o, libglew32s.a file and using it in my project it does not work

gcc src/test.c -IC:/msys64/mingw64/include -LC:/msys64/mingw64/lib -lglew32s -static -o test.exe
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Acer\AppData\Local\Temp\cc4VUWTW.o:test.c:(.text+0x53): undefined reference to `__imp_glewInit'

or if I include -DGLEW_STATIC or define it in the code:
gcc src/test.c -IC:/msys64/mingw64/include -LC:/msys64/mingw64/lib -DGLEW_STATIC -lglew32s -static -o test.exe
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0x19a): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0x63a): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xaea): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xcea): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0x161a): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0x174a): more undefined references to `__imp_wglGetProcAddress' follow
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xbea5): undefined reference to `glGetString'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xbffc): undefined reference to `glGetIntegerv'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xc009): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xc080): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xc184): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xc25f): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xc301): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+0xc3aa): more undefined references to `__imp_wglGetProcAddress' follow
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+00x11dec): undefined reference to `glGetString'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+00x12047): undefined reference to `__imp_wglGetCurrentDC'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+00x120ca): undefined reference to `__imp_wglGetProcAddress'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libglew32s.a(glew.o):glew.c:(.text+00x120ff): undefined reference to `__imp_wglGetCurrentDC'
collect2.exe: error: ld returned 1 exit status

The code is

#include <stdlib.h>
#include <stdio.h>

#include <GL/glew.h>

int main() {
    if (glewInit() != GLEW_OK) {
        fprintf(stderr, "Failed to initialize GLEW\n");
        return -1;
    }

    return 0;
}

**Comment by nigels-com** [comment]
As mentioned in [config/Makefile.msys](https://github.com/nigels-com/glew/blob/master/config/Makefile.msys#L7C14-L7C52) additional libraries need to be linked: `-lopengl32 -lgdi32 -luser32 -lkernel32`

Give that a try.

**Comment by ShohjahonOktamov** [comment]
I have forgotten to include -lopengl32 when compiling my code:
gcc src/test.c -IC:/msys64/mingw64/include -LC:/msys64/mingw64/lib -lglew32s -lopengl32 -static -o test.exe
