### ISSUE TITLE
Glew access violation in runtime after glew init has been called

### ISSUE THREAD

**Issue by Platforming-Mayhem** [nigels-com/glew#424]
Hiya,
I've been having an issue where GLEW functions keep flagging access violations at runtime. I have my project setup so that Glew is linked to my DLL and my executable. It seems like for my executable to use Glew at all, I need to called Glew Init inside of it as well, but from what I've read it seems like it should just work without me doing that. Any ideas what could be causing this?
Also I am using: https://github.com/Perlmint/glew-cmake

**Comment by nigels-com** [comment]
Could you attach some more detailed information?  The `glewInit()` step is definitely required.

What is the return code of `glewInit`?

**Comment by Platforming-Mayhem** [comment]
The return code is GLEW_OK

**Comment by Platforming-Mayhem** [comment]
<img width="508" alt="image" src="https://github.com/user-attachments/assets/0760e1fe-f477-4cb5-a45b-70baa5275204" />

**Comment by nigels-com** [comment]
The GLEW API does not guarantee that _all_ of OpenGL is available.
Only according to the GL version and available extensions.
So you'll need to make appropriate runtime checks that OpenGL you intend to use is available.
See [Usage](https://glew.sourceforge.net/basic.html).

**Comment by Platforming-Mayhem** [comment]
This function error is happening in a source file in the executable. When I move the source file from the executable to the dynamic library, there are no errors. Here's my Cmake list file:

`cmake_minimum_required(VERSION 3.8)

project(K-Engine)

set(CMAKE_CXX_STANDARD 23)
set(USE_GLU ON)
set(ONLY_LIBS ON)

find_package(OpenGL REQUIRED)

add_subdirectory(Vendors/GLFW)
add_subdirectory(Vendors/IMGUI)
add_subdirectory(Vendors/GLEW)

include_directories(Vendors/STB)

add_library(${PROJECT_NAME} SHARED 
src/K-Engine/Application.cpp
src/K-Engine/Editor.cpp
src/K-Engine/GameObject.cpp
src/K-Engine/InputManager.cpp
src/K-Engine/Material.cpp
src/K-Engine/RenderTexture.cpp
src/K-Engine/SceneManager.cpp
src/K-Engine/Serializer.cpp
src/K-Engine/Shader.cpp
src/K-Engine/Texture.cpp
src/K-Engine/Time.cpp
src/K-Engine/Transform.cpp
src/K-Engine/Window.cpp
src/K-Engine/Components/Component.cpp
)

target_sources(${PROJECT_NAME} PRIVATE assets/ignore/KEngineResources.rc)

target_compile_definitions(${PROJECT_NAME} PRIVATE K_BUILD_DLL)

target_link_libraries(${PROJECT_NAME} OpenGL::GLU)
target_link_libraries(${PROJECT_NAME} libglew_static)
target_link_libraries(${PROJECT_NAME} glfw)
target_link_libraries(${PROJECT_NAME} IMGUI)

target_include_directories(${PROJECT_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/include)
target_include_directories(${PROJECT_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_include_directories(${PROJECT_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/assets)
target_include_directories(${PROJECT_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/vendors/STB)

project(Editor)

add_executable(${PROJECT_NAME} 
src/Editor/Editor.cpp
assets/components/Camera.cpp
)

add_custom_command(
    TARGET ${PROJECT_NAME} 
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory
        ${PROJECT_SOURCE_DIR}/assets
        $<TARGET_FILE_DIR:${PROJECT_NAME}>/assets
)

target_link_libraries(${PROJECT_NAME} K-Engine)

target_include_directories(${PROJECT_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/include)
target_include_directories(${PROJECT_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_include_directories(${PROJECT_NAME} PRIVATE ${PROJECT_SOURCE_DIR}/assets)

set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "$(ProjectDir)/$(Configuration)")`

**Comment by Platforming-Mayhem** [comment]
The source file is question is Camera.cpp

**Comment by nigels-com** [comment]
Perhaps you're statically linking GLEW into a DLL, but the `glewInit` is happening in a seperate DLL or EXE?

**Comment by Platforming-Mayhem** [comment]
Glew init is being called in Window.cpp, which is in the K-Engine.dll
The Editor project links to K-Engine and calls a void function, where Glew Init is called.

**Comment by nigels-com** [comment]
Ensure that _both_ Editor and K-Engine are linking a shared (DLL) GLEW, and that neither are linking statically.
In this manner both the Editor and K-Engine are using the _same_ GLEW, not their own separate copies.

**Comment by Platforming-Mayhem** [comment]
If I understand correctly, if they are using the same library but linking against it statically separately. It means you would need to called GlewInit in both projects separately? Is there any way to get them to statically link against the same copy without having to resort to a shared library?

**Comment by nigels-com** [comment]
If K-Engine can be built and linked statically, that would be a way to have one GLEW, rather than two.

**Comment by Platforming-Mayhem** [comment]
Linking with GLEW dynamically has worked, but I still don't understand why linking with it statically would cause issues. Can you explain please?

**Comment by nigels-com** [comment]
GLEW is an API, but it also has internal state.  All of the stuff that happens during `glewInit` inititialisation gets stored in memory.  So if the K-Engine DLL is linking GLEW statically all the GLEW state is linked into that DLL.  If the Editor is also linking GLEW, that's a seperate runtime copy of the GLEW state and both "copies" would need to be initialised.

**Comment by Platforming-Mayhem** [comment]
Gotchu, thanks for the help :)
