### ISSUE TITLE
Compiling glew32.lib and glew32d.lib through the Visual Studio project files

### ISSUE THREAD

**Issue by russelltg** [nigels-com/glew#44]
How would you go about compiling these through VS - i can easily get glew32s.lib but no glew32.lib.\

Thanks!

**Comment by nigels-com** [comment]
As I recall, there are various "projects" (build targets) in the Visual Studio workspace.  Did you build all of them?

**Comment by nigels-com** [comment]
It looks like the static libraries go into lib, rather than bin.

  $ find bin lib
  ...
  bin/Debug/Win32/glew32d.dll
  ...
  lib/Debug/Win32/glew32d.exp
  lib/Debug/Win32/glew32d.lib
  lib/Debug/Win32/glew32sd.lib
  ...

**Comment by nigels-com** [comment]
Closing.
