### ISSUE TITLE
cmake: can't use the static glew library

### ISSUE THREAD

**Issue by tamaskenez** [nigels-com/glew#46]
One cannot use the static glew library from a CMake project because CMake's built-in `FindGLEW.cmake` prefers the shared library.

The official CMake-way is to allow the variable `BUILD_SHARED_LIBS` control whether to build shared or static lib and build only either one.

Another related problem is that `FindGLEW.cmake` never defines `GLEW_STATIC`. The solution is to install a config-module which is aware of the shared/static versions and defines `GLEW_STATIC` accordingly.

I will implement these changes but let me know if you're interested in such a change and if yes, I'd like to follow your preferences about the details:

- I would modify `CMakeLists.txt` to observe `BUILD_SHARED_LIBS`:
    - I can remove the option to build shared+static together (my preference)
    - I can leave the default behaviour as it is (build shared+static) and introduce `GLEW_OBSERVE_BUILD_SHARED_LIBS` with default value `OFF`
    - or introduce `GLEW_OBSERVE_BUILD_SHARED_LIBS` with default value `ON`
- I would install a config-module `glew-config.cmake` to `<prefix>/lib/cmake` which defines `GLEW_STATIC` if needed

**Comment by nigels-com** [comment]
Is there a broader cmake convention/guideline/recommendation that only a shared library ought to be built by default?  You're the second to point this out.

The current rationale is that cmake ought to match what the Makefile does, and certainly not vice-versa.  I'm not in a good position to test all the supported GNU make targets, so I'd like to avoid churning that, if possible.

Having said that, I'd like cmake support to be first class and done in a reasonably maintainable way.

**Comment by nigels-com** [comment]
Adding the complexity of GLEW_OBSERVE_BUILD_SHARED_LIBS seems a bit undesirable, on the face of it.

**Comment by tamaskenez** [comment]
The CMake `add_library` command builds a *static* library by default (not *shared*). So this part is not a convention but a fact.

But as I understand, in our case the question is whether to keep buiding both static and shared or let the user control what he/she needs.

Here are two arguments for the latter one:

- there's no support in CMake's `find_package` command to choose between shared and static. So if both are there you can only use the shared one
- Here's [this presentation](http://www.slideshare.net/DanielPfeifer1/cmake-48475415) of some CMake-expert guy and the [slide#28](http://bit.ly/1FaFVI5) says *"Don’t make libraries STATIC/SHARED unless they cannot be built otherwise"* and *"Leave the control of BUILD_SHARED_LIBS to your clients!"*

On the other hand it's also an important point to keep the behaviour of the Makefile as a reference. I would recommend the following solution if you decide to keep building both shared and static:

- The glew/CMakeLists.txt continues to build both shared and static
- The value of `BUILD_SHARED_LIBS` will be written into the generated `glew-config.cmake` config-module and will be used to choose between shared and static.
- The `FindGLEW.cmake` in the cmake-distro will continue to find only the shared one.

**Comment by tamaskenez** [comment]
Another related method is what they do in `FindBoost.cmake`: it also prefers the shared libraries but if you need the static ones you need to write:

    set(Boost_USE_STATIC_LIBS ON)
    find_package(Boost ...)

**Comment by nigels-com** [comment]
The FindBoost.cmake approach seems reasonable to me.

But I'm a bit unswayed that a vanilla GLEW build should not build all the targets - static/shared, generic/MX.  One pragmatic consideration is having patches come in that break the MX build because the contributor didn't read the documentation about the relevant targets.

- Nigel

**Comment by tamaskenez** [comment]
Okay, I'll implement a config-module where the user can select static version with GLEW_USE_STATIC_BUILDS.

The current `cmake_minimum_required` version is 2.4. Let me know if you intend to raise this to 2.8.11 (2 years old) to make code simpler. If not, I'll use the current 2.4.

**Comment by nigels-com** [comment]
Can you manage with 2.8.0? (2009)
http://www.cmake.org/Wiki/CMake_Released_Versions

If that won't fly, then OK...  (There is always the GNU make build, after all)

- Nigel

**Comment by tamaskenez** [comment]
Okay, I'll check what is missing from 2.8 and try it.
