### ISSUE TITLE
Building from git-source throws errors on OS X Yosemite

### ISSUE THREAD

**Issue by BRabbit27** [nigels-com/glew#47]
I downloaded the code using git and try to build glew from it. The commands used were

```
export GLEW_DEST=/usr/local/glew
make extensions
make
```

and the resulting error is

```
ld: dylib lib/libGLEW.dylib missing LC_ID_DYLIB load command file 'lib/libGLEW.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

am I doing something wrong during the compilation?

**Comment by nigels-com** [comment]
Do you mind checking if 1.12.0 has the same problem. I'm still on OSX 10.9...

**Comment by nigels-com** [comment]
See also: http://sourceforge.net/p/glew/bugs/270/

**Comment by nigels-com** [comment]
Some more of the failing build log might also help shed some light.

**Comment by BRabbit27** [comment]
Sorry to ask but, where/how can I see the build log?

**Comment by nigels-com** [comment]
Everything on the console following the make command, would be helpful.

**Comment by BRabbit27** [comment]
I downloaded today the latest commit cbd0dce3c5 and run the same commands as when opened the issue in OS X 10.10.5. The resulting output is the following

```
$ make
mkdir lib
cc -DGLEW_NO_GLU -DGLEW_BUILD -O2 -Wall -W -Iinclude -dynamic -fno-common -ansi -pedantic -fPIC  -o tmp/darwin/default/shared/glew.o -c src/glew.c
cc -dynamiclib -install_name /usr/local/glew/lib/libGLEW.1.13.0.dylib -current_version 1.13.0 -compatibility_version 1.13 -o lib/libGLEW.1.13.0.dylib tmp/darwin/default/shared/glew.o  -framework OpenGL 
ln -sf libGLEW.1.13.0.dylib lib/libGLEW.1.13.dylib
ln -sf libGLEW.1.13.0.dylib lib/libGLEW.dylib
strip -x lib/libGLEW.1.13.0.dylib
cc -DGLEW_NO_GLU -DGLEW_STATIC -O2 -Wall -W -Iinclude -dynamic -fno-common -ansi -pedantic -fPIC  -o tmp/darwin/default/static/glew.o -c src/glew.c
ar rv lib/libGLEW.a tmp/darwin/default/static/glew.o
ar: creating lib/libGLEW.a
a - tmp/darwin/default/static/glew.o
strip -x lib/libGLEW.a
sed \
		-e "s|@prefix@|/usr|g" \
		-e "s|@libdir@|/usr/local/glew/lib|g" \
		-e "s|@exec_prefix@|/usr/local/glew/bin|g" \
		-e "s|@includedir@|/usr/local/glew/include/GL|g" \
		-e "s|@version@|1.13.0|g" \
		-e "s|@cflags@||g" \
		-e "s|@libname@|GLEW|g" \
		-e "s|@requireslib@|glu|g" \
		< glew.pc.in > glew.pc
cc -DGLEW_NO_GLU -DGLEW_MX -DGLEW_BUILD -O2 -Wall -W -Iinclude -dynamic -fno-common -ansi -pedantic -fPIC  -o tmp/darwin/mx/shared/glew.o -c src/glew.c
cc -dynamiclib -install_name /usr/local/glew/lib/libGLEWmx.1.13.0.dylib -current_version 1.13.0 -compatibility_version 1.13 -o lib/libGLEWmx.1.13.0.dylib tmp/darwin/mx/shared/glew.o  -framework OpenGL 
ln -sf libGLEWmx.1.13.0.dylib lib/libGLEWmx.1.13.dylib
ln -sf libGLEWmx.1.13.0.dylib lib/libGLEWmx.dylib
strip -x lib/libGLEWmx.1.13.0.dylib
cc -DGLEW_NO_GLU -DGLEW_MX -DGLEW_STATIC -O2 -Wall -W -Iinclude -dynamic -fno-common -ansi -pedantic -fPIC  -o tmp/darwin/mx/static/glew.o -c src/glew.c
ar rv lib/libGLEWmx.a tmp/darwin/mx/static/glew.o
ar: creating lib/libGLEWmx.a
a - tmp/darwin/mx/static/glew.o
strip -x lib/libGLEWmx.a
sed \
		-e "s|@prefix@|/usr|g" \
		-e "s|@libdir@|/usr/local/glew/lib|g" \
		-e "s|@exec_prefix@|/usr/local/glew/bin|g" \
		-e "s|@includedir@|/usr/local/glew/include/GL|g" \
		-e "s|@version@|1.13.0|g" \
		-e "s|@cflags@|-DGLEW_MX|g" \
		-e "s|@libname@|GLEWmx|g" \
		-e "s|@requireslib@|glu|g" \
		< glew.pc.in > glewmx.pc
mkdir bin
cc -DGLEW_NO_GLU -O2 -Wall -W -Iinclude -dynamic -fno-common -ansi -pedantic -fPIC  -o tmp/darwin/default/shared/glewinfo.o -c src/glewinfo.c
cc -O2 -Wall -W -Iinclude -dynamic -fno-common -ansi -pedantic -fPIC -o bin/glewinfo tmp/darwin/default/shared/glewinfo.o -Llib  -lGLEW  -framework OpenGL
clang: warning: argument unused during compilation: '-ansi'
ld: dylib lib/libGLEW.dylib missing LC_ID_DYLIB load command file 'lib/libGLEW.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/glewinfo] Error 1
```

**Comment by tamaskenez** [comment]
On my 10.10.5 the same commit builds fine. Could be some local issue.

    $ cc --version
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

**Comment by BRabbit27** [comment]
This is my configuration
```
$ cc --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
Looks pretty much the same. Could you post the commands you are executing?

**Comment by BRabbit27** [comment]
I tried to debug the makefile to see what is missing. Using `make -n` the following lines are the ones to be executed

```
cc -O2 -Wall -W -Iinclude -dynamic -fno-common -ansi -pedantic -fPIC -o bin/glewinfo tmp/darwin/default/shared/glewinfo.o -Llib  -lGLEW  -framework OpenGL
```

and that line is the one that's breaking the make. Any clue?

**Comment by BRabbit27** [comment]
Ok, somehow the `strip` commands are causing the error of `ld: dylib lib/libGLEW.dylib missing LC_ID_DYLIB load command file 'lib/libGLEW.dylib' for architecture x86_64` I commented out all the lines calling the strip command and I was able to build glew, haven't tried it yet though.

**Comment by nigels-com** [comment]
Oh!  Specify STRIP= on the command line, to disable that step.

**Comment by BRabbit27** [comment]
But should I actually disable the strip command or should it work even with it?

**Comment by nigels-com** [comment]
Sounds like a bug or incompatibility between the compiler and strip.  Stripping is optional, so use STRIP= to skip it.

**Comment by BRabbit27** [comment]
Hope @tamaskenez share the building commands, because apparently it worked for him smoothly. I'll try the STRIP= and try to build a simple program.

**Comment by BRabbit27** [comment]
Find a solution to building and linking to my app in the issue #13

**Comment by tamaskenez** [comment]
@BRabbit27 I used the exact 3 command from your first post

**Comment by BRabbit27** [comment]
@nigels-com @tamaskenez do you have any idea on what could be the problem? I haven't made any major configuration change on my system.

**Comment by tamaskenez** [comment]
I'm not familiar with the LC_ID_DYLIB setting but let me know what should I check on my system and I'll post it here.
Also you can try to build it with CMake. You need the CMake tool in your path (the macports version is fine) and simply launch `cmake-testbuild.sh`

**Comment by BRabbit27** [comment]
@tamaskenez yes, as I commented already, using cmake builds correctly the library. I guess is the same kind of building between Makefile and Cmake, so I don't understand why one works and the other don't.

**Comment by nigels-com** [comment]
I just might have to dust off my busted up old MacBook Pro and see if it can cope with Yosemite.

**Comment by nigels-com** [comment]
(I'm still holding out for a new MacBook Pro, even though Santa failed to deliver on that)

**Comment by nigels-com** [comment]
These worked for me on 10.12.1, closing.
Thanks for the report.

```
$ make extensions clean all SYSTEM=darwin
```

```
$ make extensions clean all SYSTEM=darwin-universal
...
$ file lib/libGLEW.dylib 
lib/libGLEW.dylib: Mach-O universal binary with 2 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64: Mach-O 64-bit dynamically linked shared library x86_64]
lib/libGLEW.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
lib/libGLEW.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
```
