### ISSUE TITLE
glGetString(GL_EXTENSIONS) returns NULL

### ISSUE THREAD

**Issue by mchiasson** [nigels-com/glew#51]
I'm on Linux 3.16, MESA OpenGL driver 10.1.3, using OpenGL 3+ and none of the extensions can be detected by GLEW because `glGetString(GL_EXTENTIONS)` returns NULL on my system:

```C++
  /* query opengl extensions string */
  extStart = glGetString(GL_EXTENSIONS);
```

if I do this, it works fine:
```C++
    GLint n;
    glGetIntegerv(GL_NUM_EXTENSIONS, &n);
    if (n > 0)
    {
        const char** extensions = (const char**)malloc(n * sizeof(char*));
        GLint i;
        for (i = 0; i < n; i++)
        {
            extensions[i] = (char*)glGetStringi(GL_EXTENSIONS, i);
        }
    }
```

**Comment by mchiasson** [comment]
oh, there is already an outstanding pull request for this issue (https://github.com/nigels-com/glew/pull/24) I will close this issue since someone is already proposing a fix.

**Comment by nigels-com** [comment]
Yes, there have been various efforts to support core contexts, but nothing that has been accepted into the mainline yet.  I must get back to that...

- Nigel
