### ISSUE TITLE
You have to be joking on not setting up /usr/local prefix

### ISSUE THREAD

**Issue by mdriftmeyer** [nigels-com/glew#52]
in your make install. I'll grant your laziness on Cmake out of tree building being useless, but polluting the /usr/ and not installing default under /usr/local/ is pathetic.

**Comment by nigels-com** [comment]
I'd assume it's been that way for a very long time.  I don't have a strong opinion one way or the other.  Is this kind of thing covered by a LSB or FHS document, or merely broader convention?

**Comment by badsector** [comment]
/usr is used by the distribution package manager and can clash with it. 

Also `Makefile.linux` seems to force lib/lib64 for x86_64 systems which isn't the proper place everywhere. In Debian (and derivatives) you'd want lib/x86_64-linux-gnu instead, otherwise pkg-config wont be able to use GLEW.

**Comment by rossburton** [comment]
Packages should default to /usr/local unless told otherwise, so as not to conflict with the distro-managed install in /usr.

Also as @ghost says, instead of assuming you know that the library path is $CMAKE_INSTALL_PREFIX/lib let the user override them.  This is what https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html is for.

**Comment by tamaskenez** [comment]
@mdriftmeyer @ghost @rossburton Could you guys try to debug the `/usr` issue in your CMake builds? It should not really happen. `CMAKE_INSTALL_PREFIX` defaults to `/usr/local` in all CMake versions at least from 2.6 up. And glew's CMakeLists.txt does not mess with it. I've just tried it to be sure and it does install to `/usr/local` (CMake 3.4.3, darwin15)

**Comment by nlichtenberg** [comment]
An according hint should be added to the README.txt. Simply following the steps
`make`
`sudo make install`
seemed to overwrite the glew 1.10 library which shipped with Ubuntu and broke Unity in my case.

**Comment by rossburton** [comment]
Just rediscovered this.  The issue is in the Makefile, so CMake doing the right thing isn't relevant.
