### ISSUE TITLE
Mac OS X: some core functions generate EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by livingcreative** [nigels-com/glew#61]
I'm using GLEW for my OpenGL project and primary development platform is Windows. I use forward OpenGL 4.0 context and all work just fine on Windows.

When I ported code to OS X some of core functions seems not to be initialized (are NULL). For example, glGenSamplers (which is definitely core function in 4x) throws EXC_BAD_ACCESS. I tried to create 3x and 4x contexts (with NSOpenGLContext) - both give same error. However, when I use standard gl3.h header (OpenGL/gl3.h) instead of using GLEW all core functions work ok, so this is not hardware or driver issue.

My OS X version is 10.10.2 (Yosemite) and video card is AMD R9 280X

**Comment by nigels-com** [comment]
The next of release of GLEW is likely to be based on the work in the core-context5 branch.  I've been testing that mainly on Linux and Windows.  Hopefully it will "just work" for Mac, but I'd be happy to prioritize any issues that you come across with that.

- Nigel

**Comment by livingcreative** [comment]
Thanks for reply. I'll wait for next release.

I thought that might not be an issue with the GLEW library itself. I tried to copy and use "glewgetprocaddress" function directly to retrieve address of some functions that fail and there were no luck. It seems that something changed in newer versions of OS X. Some functions used inside "glewgetprocaddress"  reported as deprecated, maybe this is the cause.

**Comment by nigels-com** [comment]
There is some progress on this, and positive reports concerning Mac OS X.  However, Windows is currently broken, in the master branch, unfortunately.  I don't have a Mac at the moment, so I'm mostly relying on contributions for that, at the moment.

**Comment by nigels-com** [comment]
Looks good to me on 10.12.1, thanks for the report.

```
$ bin/glewinfo
...
GLEW version 2.0.0
Running on a Intel(R) Iris(TM) Graphics 540 from Intel Inc.
OpenGL version 2.1 INTEL-10.20.25 is supported
```

And

```
$ bin/glewinfo -version 3.2 -profile core
...
GLEW version 2.0.0
Running on a Intel(R) Iris(TM) Graphics 540 from Intel Inc.
OpenGL version 4.1 INTEL-10.20.25 is supported
...
GL_ARB_sampler_objects:                                        OK 
-----------------------
  glBindSampler:                                               OK
  glDeleteSamplers:                                            OK
  glGenSamplers:                                               OK
  glGetSamplerParameterIiv:                                    OK
  glGetSamplerParameterIuiv:                                   OK
  glGetSamplerParameterfv:                                     OK
  glGetSamplerParameteriv:                                     OK
  glIsSampler:                                                 OK
  glSamplerParameterIiv:                                       OK
  glSamplerParameterIuiv:                                      OK
  glSamplerParameterf:                                         OK
  glSamplerParameterfv:                                        OK
  glSamplerParameteri:                                         OK
  glSamplerParameteriv:                                        OK
```
