### ISSUE TITLE
Compile failure on Ubuntu 14.04

### ISSUE THREAD

**Issue by jasjuang** [nigels-com/glew#65]
when I clone the repo and simply type make, the error is shown below

make: *** No rule to make target `src/glew.c', needed by `tmp/linux/default/shared/glew.o'.  Stop.

It seems that there is no glew.c exist in the src folder, can someone help? Thanks

**Comment by nigels-com** [comment]
See: http://glew.sourceforge.net/advanced.html

Usually, it's recommended to download a release tarball:
https://sourceforge.net/projects/glew/files/glew/1.13.0/glew-1.13.0.tgz/download

**Comment by jasjuang** [comment]
Downloading the tarball works... but why would the repo itself be missing files?

**Comment by nigels-com** [comment]
This is becoming the #1 FAQ this year.
See: https://github.com/nigels-com/glew/issues/31

**Comment by jasjuang** [comment]
Thanks for the explanation
