### ISSUE TITLE
Glew Cmake

### ISSUE THREAD

**Issue by ackoujens** [nigels-com/glew#69]
If you were looking for glew using cmake instead of make. (Saw `cmake-testbuild.sh` popping up in your repo)
https://github.com/Perlmint/glew-cmake this project did it pretty well.

I noticed I could generate a perfectly working project in the same fashion I did with the opengl-boilerplate.
Instead I used this guys repo which I find a bit more interesting than the opengl-boilerplate.
https://github.com/ArthurSonzogni/OpenGL_CMake_Skeleton

Could've forked your version of glew and simply copy paste the cmake file but I don't want to take credit for something I didn't put my effort into.

Hope it helps for your cmake test build

**Comment by nigels-com** [comment]
I don't tend to use cmake for GLEW, but I'm happy to accept contributions to what's there in build/cmake.
