### ISSUE TITLE
Replace macro with inline functions

### ISSUE THREAD

**Issue by pixeljetstream** [nigels-com/glew#71]
Hi,
with the removal of MX support and added core, it would be nice to convert from the macro usage to inline functions. Currently am doing this in "post" by parsing the glew headers and replacing the macros with some lua scripts, but it would be nice if the stock GLEW offers this functionality. I've also added a GLEW_USER_ASSERT macro that can be defined optionally, to prevent calling a NULL function pointer.

GLEW_FUN_EXPORT PFNGLNAMEDPROGRAMLOCALPARAMETERI4IEXTPROC __glewNamedProgramLocalParameterI4iEXT;
__inline void glNamedProgramLocalParameterI4iEXT(GLuint program,GLenum target,GLuint index,GLint x,GLint y,GLint z,GLint w){
GLEW_USER_ASSERT(__glewNamedProgramLocalParameterI4iEXT);
__glewNamedProgramLocalParameterI4iEXT(program,target,index,x,y,z,w);}

one benefit of inline is that it works well with showing the function arguments in IDEs

**Comment by nigels-com** [comment]
I think this would make GLEW would break compatibility with this change, unfortunately.  There is code that directly queries and sets function pointers.  Which would clearly break for inclined functions.  Perhaps Regal instead? LOL!

**Comment by nigels-com** [comment]
Aside from burning bridges in terms of adding back MX mode, it does seem like GLEW_GET_FUN could be conditionalized to opt-in to inlined functions.  But that might not suffice for IDEs.

**Comment by pixeljetstream** [comment]
well the function pointer "set" in glew.c could be replaced by not using the macro and instead the mangled name directly?

it only breaks code compatibility if users assigned function pointers themselves using the macros outside of the library.

**Comment by nigels-com** [comment]
Current thought is to only `#define GLEW_GET_FUN` if it's not already defined.  This will allow for wrapper functions declared elsewhere to be used instead of directly mapping glFunc to __glewFunc, as is the usual arrangement.

**Comment by nigels-com** [comment]
There is a change to the master branch to avoid defining GLEW_GET_FUN etc, unless necessary.  This leaves the binary API untouched, but opens the door to having an alternative layer of macros or functions for calling into OpenGL.  I don't have any immediate plans in regard to naming or generating alternatives to `glew.h`, but it's a first step.

**Comment by nigels-com** [comment]
Closing, unless there is anything further for this.
