### ISSUE TITLE
Is linking libGL necessary with GLEW?

### ISSUE THREAD

**Issue by jasjuang** [nigels-com/glew#73]
Suppose I have code 

TestExample.cpp
```
#include "GL/glew.h"
int main(){
  glewInit();
  GLuint id = 0;
  glGenTextures(1, &id);

  return 0;
}
```
g++ TestExample.cpp -lGLEW returns a compile error

/usr/bin/ld: /tmp/ccwGckkm.o: undefined reference to symbol 'glGenTextures'
//usr/lib/nvidia-352/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I need to compile it with g++ Example.cpp -lGLEW -lGL for it to pass compilation.

The confusing part for me is if I move the glew portion into a class and compile it as a library, no linking against libGL is needed and it compiles fine and runs fine. For example,

TestExample.cpp
```
#include "Test.h"
int main(){
  Test test;
  test.Print();
  return 0;
}
```
Test.h
```
class Test{
 public:
  Test();
  ~Test();

  void Print();
};
```
Test.cpp
```
#include "Test.h"
#include "GL/glew.h"
#include <iostream>

Test::Test(){}
Test::~Test(){}

void Test::Print(){
  glewInit();

  GLuint id = 0;
  glGenTextures(1, &id);

  std::cout << "test!" << std::endl;
}
```
g++ -fPIC -I. -o Test.o -c Test.cpp
g++ -shared -Wl,-soname,libTest.so -o libTest.so Test.o -lGLEW
g++ TestExample.cpp -L. -lTest
./a.out shows test!

Please advice, thanks!

**Comment by nigels-com** [comment]
What you're observing here is that gcc behaves differently for linking executables and shared libraries. Shared libs are allowed to have unresolved symbols, while executables are not.  So in this case the ,so would work fine providing the necessary symbols are available at runtime, via some other dependency on libGL.so.

In a nutshell, yes, -lGL is expected by libGLEW.so.

- Nigel

**Comment by jasjuang** [comment]
Thanks a lot for the explanation!
