### ISSUE TITLE
Valid context but Missing GL version error

### ISSUE THREAD

**Issue by myrage2000** [nigels-com/glew#76]
Hey
i'm using glew and glfw3.
In my code, I init glfw3 first, then I create a window and its context, and then I try to initialize glew.
I get the "missing gl version" error.
I compiled on windows sources myself.
Here are my preprocessors for compiling glfw : 

> _GLFW_WIN32;_GLFW_WGL;_GLFW_USE_OPENGL;_GLFW_BUILD_DLL;

and for glew :

> WIN32;WIN32_LEAN_AND_MEAN;VC_EXTRALEAN;GLEW_BUILD;

Here is my code :

	`GLFWwindow* window;
	glfwSetErrorCallback(error_callback);
        if (!glfwInit())
		exit(EXIT_FAILURE);
	window = glfwCreateWindow(640, 480, "Simple example", NULL, NULL);
	if (!window)
	{
		glfwTerminate();
		exit(EXIT_FAILURE);
	}
	glfwMakeContextCurrent(window);
	std::cout << glGetString(GL_VERSION) << std::endl;

	glewExperimental = true;
	GLenum err = glewInit();
	if (err != GLEW_OK) {
		std::cerr << "Failed to init GLEW !" << std::endl << glewGetErrorString(err) << std::endl;
		glfwTerminate();
		return 1;
	}`
glGetString(GL_VERSION) does return my opengl version ! (4.5.0)
And I tried with glewExperimental = false too

After some debugging, I found that this is causing the error : 
`  getString = (PFNGLGETSTRINGPROC)  glewGetProcAddress((const GLubyte*)"glGetString");
  if (!getString)
    return GLEW_ERROR_NO_GL_VERSION;`
That means glew can't get that string...

Can somebody help me please ?

**Comment by CalicoBay** [comment]
On Windows glGetString is already available so you have no need to glewGetProcAddress, which is actually wglGetProcAddress. So just use glGetString directly. Make sure you do the same a little later in the same function during an "else" that doesn't get called much.

**Comment by nigels-com** [comment]
Can you confirm that GLEW 1.13.0 (current release version) does indeed work as expected?  This lookup is new for the next release, but I'd like to know why it's not working on Windows.

**Comment by myrage2000** [comment]
Yes I downloaded the source of 1.13.0 and it's working fine
Thanks for your help

**Comment by CalicoBay** [comment]
As a form of self education, I'm from the Windows/DirectX camp, I cloned from https://github.com/nigels-com/glew.git and then did the whole Cygwin thing and extracted from OpenGL.org etc. It was the glew.c that resulted which had the getString problem. I then debugged and patched the code as above. I was quite confused at first because glew.c is not included with the clone and I'm used to being spoon fed by SDKs. I still don't really know what forms glew.c. I suppose it is buried in CMakeLists.txt somewhere but haven't had time to sus it out yet. I was introduced to glew et al by Nvidia's OptiX and got curious.

**Comment by tszirr** [comment]
Same issue here, wglGetProcAddress does not support retrieving glGetString. Also see annoted line in corresponding commit, https://github.com/nigels-com/glew/commit/23438663d6e2d3afd49727fd33466dd7b5e60257#diff-87cc1d764de01c951edbf22da0180079R85

**Comment by nigels-com** [comment]
Yes, unfortunately this **wglGetProcAddress** loading of glGetString is not valid on Windows.  We'll need to #ifdef _WIN32 our way around this, I think.  Sorry for the breakage, I think this is the main blocker for a GLEW 2.0 release.

**Comment by nigels-com** [comment]
I put a fix into master for this.  If anyone can confirm this on Windows, that would be great:
[141.1/glew-2.0.0.zip](https://glew.s3.amazonaws.com/nigels-com/glew/141/141.1/glew-2.0.0.zip)

**Comment by tszirr** [comment]
Thanks, pulled master branch and works on my windows machine now.

**Comment by myrage2000** [comment]
Yes now it works !
Thanks
