### ISSUE TITLE
Setting STRIP='' doesn't stop the test binaries from being stripped

### ISSUE THREAD

**Issue by rossburton** [nigels-com/glew#77]
The top of the makefile says to set STRIP='' to stop the binaries from being stripped.  However the binaries (as installed by install.bin) uses install -s instead of $(STRIP) so they're always stripped.

**Comment by nigels-com** [comment]
Yes, confirming that.  I suppose we could also have an override for **install** to control the flags being used there as well.

**Comment by nigels-com** [comment]
I clarified the note in the Makefile concerning the STRIP variable.  I guess you'd need to workaround that by installing with the appropriate flags.  Thanks for the report.
