### ISSUE TITLE
__eglewGetDisplay defined but never loaded

### ISSUE THREAD

**Issue by tfogal** [nigels-com/glew#80]
Hi Nigel et al.,

I'm trying to use GLEW from git to get EGL.  It looks like GLEW is redefining e.g. "eglGetDisplay", but it never actually loads the function pointer.
Is it just that the support is currently incomplete?  What is the current status?

Thanks!

**Comment by nigels-com** [comment]
Hi Tom.  Yes, the EGL support is new, and possibly has gaps.  I'll take a fresh look.  You're on Linux?

**Comment by tfogal** [comment]
Yes, Linux only for the moment.

**Comment by nigels-com** [comment]
Tom, it appears to be in ` _glewInit_EGL_VERSION_1_0` that `eglGetDisplay` is being initialized.  For example:

```
$ make SYSTEM=linux-egl
...
$ export LD_LIBRARY_PATH=lib
$ bin/glewinfo | grep eglGetDisplay
  eglGetDisplay:                                               OK
```

Are you building GLEW with `-DGLEW_EGL`?

**Comment by tfogal** [comment]
Hah I was just logging in to comment---I was forgetting the -DGLEW_EGL.
Mea culpa, and sorry for the noise!
