### ISSUE TITLE
Discourage building from bare git repo, use release snapshot instead

### ISSUE THREAD

**Issue by ghost** [nigels-com/glew#85]
I was trying to use cmake and the provided VS12 solution but got the following errors.

**Command to build with cmake and results**
`cmake -G "Visual Studio 12 2013 Win64" ./cmake`

$ cmake -G "Visual Studio 12 2013 Win64" ./cmake
-- The C compiler identification is MSVC 18.0.21005.1
-- The CXX compiler identification is MSVC 18.0.21005.1
-- Check for working C compiler using: Visual Studio 12 2013 Win64
-- Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: opengl32
-- Configuring done
CMake Error at CMakeLists.txt:89 (add_library):
  Cannot find source file:

```
C:/Users/Me/Github/glew/include/GL/wglew.h
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:160 (add_executable):
  Cannot find source file:

```
C:/Users/Me/Github/glew/src/glewinfo.c
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:170 (add_executable):
  Cannot find source file:

```
C:/Users/Me/Github/glew/build/visualinfo.rc
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: glewinfo
CMake Error: CMake can not determine linker language for target: glew_s
CMake Error: CMake can not determine linker language for target: visualinfo
CMake Error: CMake can not determine linker language for target: glew
CMake Error: CMake can not determine linker language for target: glew
CMake Error in CMakeLists.txt:
  Exporting the target "glew" is not allowed since its linker language cannot
  be determined

CMake Error: CMake can not determine linker language for target: glew
CMake Error in CMakeLists.txt:
  Exporting the target "glew" is not allowed since its linker language cannot
  be determined

CMake Error: CMake can not determine linker language for target: glew
CMake Error in CMakeLists.txt:
  Exporting the target "glew" is not allowed since its linker language cannot
  be determined

CMake Error: CMake can not determine linker language for target: glew
CMake Error in CMakeLists.txt:
  Exporting the target "glew" is not allowed since its linker language cannot
  be determined

CMake Error: CMake can not determine linker language for target: glew
CMake Error in CMakeLists.txt:
  Exporting the target "glew" is not allowed since its linker language cannot
  be determined

CMake Error: CMake can not determine linker language for target: glew_s
CMake Error in CMakeLists.txt:
  Exporting the target "glew_s" is not allowed since its linker language
  cannot be determined

CMake Error: CMake can not determine linker language for target: glew_s
CMake Error in CMakeLists.txt:
  Exporting the target "glew_s" is not allowed since its linker language
  cannot be determined

CMake Error: CMake can not determine linker language for target: glew_s
CMake Error in CMakeLists.txt:
  Exporting the target "glew_s" is not allowed since its linker language
  cannot be determined

CMake Error: CMake can not determine linker language for target: glew_s
CMake Error in CMakeLists.txt:
  Exporting the target "glew_s" is not allowed since its linker language
  cannot be determined

CMake Error: CMake can not determine linker language for target: glew_s
CMake Error in CMakeLists.txt:
  Exporting the target "glew_s" is not allowed since its linker language
  cannot be determined

-- Generating done
-- Build files have been written to: C:/Users/Me/Github/gle
w/build

**Results from VS12 provided solution**
1>------ Build started: Project: glew_static, Configuration: Debug Win32 ------
2>------ Build started: Project: glew_shared, Configuration: Debug Win32 ------
1>  glew.c
1>c1 : fatal error C1083: Cannot open source file: '....\src\glew.c': No such file or directory
2>  glew.c
2>c1 : fatal error C1083: Cannot open source file: '....\src\glew.c': No such file or directory
3>------ Build started: Project: glewinfo, Configuration: Debug Win32 ------
4>------ Build started: Project: visualinfo, Configuration: Debug Win32 ------
4>  visualinfo.c
3>  glewinfo.c
3>c1 : fatal error C1083: Cannot open source file: '....\src\glewinfo.c': No such file or directory
4>....\src\visualinfo.c(36): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

I remember compiling on Mac OS and executing `make extensions` before attempting cmake and it worked. Actually, the aforementioned command created a directory called include that is not present when build on windows with cmake or vs. What should I do be able to do `make extensions` but in windows to build from source?

Cheers

**Comment by nigels-com** [comment]
See: https://github.com/nigels-com/glew/issues/31

Try: http://sourceforge.net/projects/glew/files/glew/snapshots/glew-20160402.tgz/download

**Comment by nigels-com** [comment]
I'm tempted to re-purpose this issue along the the lines that:
_cmake ought to recommend a source .zip file download for windows if glew.c etc are not found._

**Comment by Ubiquite** [comment]
Same issue here, it's confusing not to be able to build from github.

**Comment by DarthPJB** [comment]
Not being able to build from github isn't just confusing, it's a showstopper for commercial use.
Admittedly I'm working on a hobby project now, so I'm not NDA'ed - but the short of the matter is, my previous employer refused to use any project that we couldn't use as a git-sub-module.

Further the GLEW documentation clearly says I can "A MS Visual Studio project is provided in the build/vc6 directory." - this is absolutely false.

That said, I'm not some complainer - If someone can in a couple of sentences explain what needs to be done for GLEW to be built on windows (even if that includes writing Cmake instructions) I will **GLADLY do the work and post a pull request. **
GLEW has been a favourite library of mine for a long time, however "download the binaries" isn't enough for someone like myself.

**Comment by nigels-com** [comment]
I agree that assumptions and expectations have changed over time.  The challenge is that the code generation all being GNU make, perl and sed has been hit and miss on Windows, and getting daily complaints about that is not so fun.  (Hence the advice to grab the binaries or .zip file)

Broadly I'd like the make/perl/sed/bash to be reimplemented in Python for better portability and maintainability.  (I'm no perl wizard, I avoid dealing with that as much as possible) . It's not a whole lot of code, and at least it's easy to look in a diff tool where things match or not.

Converting the source release tarballs into a seperate repository is something I'd seriously consider.  I'd be a reluctant to have all that bulk in the main repository, though, since it's essentially irrelevant to the day-to-day maintenance of GLEW, from a code-generation point of view.  

Beside those points I'm still a bit of a cmake skeptic, even though I use it day-in day-out.  It doesn't seem to be going away, but all of that convoluted pseudo-scripting for the sake of compiling one file of C code _still_ seems like overkill, aside from that being the normal workflow nowadays.

So, what would first-class Windows support look like to you?  Just git, Python and Cmake and the rest just goes by the wayside?

-- Nigel

**Comment by nigels-com** [comment]
Pointing to the git-module-and-cmake-friendly alternative, for now:
https://github.com/Perlmint/glew-cmake
