### ISSUE TITLE
current snapshot fails to build

### ISSUE THREAD

**Issue by egonalter** [nigels-com/glew#87]
OS: Linux (openSUSE_Tumbleweed)

# git checkout origin/master
HEAD is now at 180db26... cmake fixup for non-Windows
# git clean -fdx
# make
mkdir lib
make: *** No rule to make target 'src/glew.c', needed by 'tmp/linux/default/shared/glew.o'.  Stop.
# git clean -fdx && cd build
# cmake ./cmake
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib64/libGL.so  
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Configuring done
CMake Error at CMakeLists.txt:89 (add_library):
  Cannot find source file:

    /source/dri-project/glew/include/GL/wglew.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:160 (add_executable):
  Cannot find source file:

    /source/dri-project/glew/src/glewinfo.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: glew
CMake Error: Cannot determine link language for target "glew".
CMake Error: Cannot determine link language for target "glew_s".
CMake Error: CMake can not determine linker language for target: glew_s
CMake Error: CMake can not determine linker language for target: glewinfo
CMake Error: Cannot determine link language for target "glewinfo".
CMake Error: CMake can not determine linker language for target: glew
CMake Error in CMakeLists.txt:
  Exporting the target "glew" is not allowed since its linker language cannot
  be determined

CMake Error in CMakeLists.txt:
  Exporting the target "glew" is not allowed since its linker language cannot
  be determined

CMake Error: CMake can not determine linker language for target: glew_s
CMake Error in CMakeLists.txt:
  Exporting the target "glew_s" is not allowed since its linker language
  cannot be determined

CMake Error in CMakeLists.txt:
  Exporting the target "glew_s" is not allowed since its linker language
  cannot be determined

-- Generating done
-- Build files have been written to: /source/dri-project/glew/build

**Comment by nigels-com** [comment]
See: https://github.com/nigels-com/glew/issues/31
