### ISSUE TITLE
Wrong values for NV_command_list extension

### ISSUE THREAD

**Issue by Nau3D** [nigels-com/glew#89]
Hi,

In glew-20160131.tgz the defines are missing the letters. In glew.h you find:

#define GL_ALPHA_REF_COMMAND_NV 0x000
#define GL_BLEND_COLOR_COMMAND_NV 0x000
#define GL_LINE_WIDTH_COMMAND_NV 0x000
#define GL_POLYGON_OFFSET_COMMAND_NV 0x000
#define GL_STENCIL_REF_COMMAND_NV 0x000
#define GL_TERMINATE_SEQUENCE_COMMAND_NV 0x0000
#define GL_UNIFORM_ADDRESS_COMMAND_NV 0x000

where, according to the extension specs, it should be:

#define GL_UNIFORM_ADDRESS_COMMAND_NV                       0x000a
#define GL_BLEND_COLOR_COMMAND_NV                           0x000b
#define GL_STENCIL_REF_COMMAND_NV                           0x000c
#define GL_LINE_WIDTH_COMMAND_NV                            0x000d
#define GL_POLYGON_OFFSET_COMMAND_NV                        0x000e
#define GL_ALPHA_REF_COMMAND_NV                             0x000f

Keep up the excellent work :-)

Best Regards,

António

**Comment by nigels-com** [comment]
Yikes!  Thanks!

**Comment by nigels-com** [comment]
Fixed. Thanks for the report.

```
#define GL_TERMINATE_SEQUENCE_COMMAND_NV 0x0000
#define GL_NOP_COMMAND_NV 0x0001
#define GL_DRAW_ELEMENTS_COMMAND_NV 0x0002
#define GL_DRAW_ARRAYS_COMMAND_NV 0x0003
#define GL_DRAW_ELEMENTS_STRIP_COMMAND_NV 0x0004
#define GL_DRAW_ARRAYS_STRIP_COMMAND_NV 0x0005
#define GL_DRAW_ELEMENTS_INSTANCED_COMMAND_NV 0x0006
#define GL_DRAW_ARRAYS_INSTANCED_COMMAND_NV 0x0007
#define GL_ELEMENT_ADDRESS_COMMAND_NV 0x0008
#define GL_ATTRIBUTE_ADDRESS_COMMAND_NV 0x0009
#define GL_UNIFORM_ADDRESS_COMMAND_NV 0x000a
#define GL_BLEND_COLOR_COMMAND_NV 0x000b
#define GL_STENCIL_REF_COMMAND_NV 0x000c
#define GL_LINE_WIDTH_COMMAND_NV 0x000d
#define GL_POLYGON_OFFSET_COMMAND_NV 0x000e
#define GL_ALPHA_REF_COMMAND_NV 0x000f
#define GL_VIEWPORT_COMMAND_NV 0x0010
#define GL_SCISSOR_COMMAND_NV 0x0011
#define GL_FRONT_FACE_COMMAND_NV 0x0012
```

**Comment by nigels-com** [comment]
Fresh source tarballs here:
https://glew.s3.amazonaws.com/index.html?prefix=nigels-com/glew/159/159.1/

**Comment by Nau3D** [comment]
Great. Thank You.

António
