### ISSUE TITLE
try to build on linux (ubuntu 16.04)

### ISSUE THREAD

**Issue by byteshelter** [nigels-com/glew#90]
Hi all,

i did a simple git clone to get the sources and typed "make" like the documentation tells me but i only get something like: make: *** No Rule found to build „src/glew.c“, 
  needed to build  „tmp/linux/default/shared/glew.o“. Finish.

.. what am i doing wrong ??

**Comment by nigels-com** [comment]
https://sourceforge.net/projects/glew/files/glew/1.13.0/glew-1.13.0.tgz/download
