### ISSUE TITLE
unresolved external symbol errors

### ISSUE THREAD

**Issue by jawhster** [nigels-com/glew#93]
I've followed http://glew.sourceforge.net/install.html and still receiving errors. Linked project with glew32.lib, glu32.lib, and opengl32.lib on Windows. What is going on?

```
#include <cmath>
#include <iostream>
#include <sstream>
#include <vector>
#include "vecmath.h"
#include <fstream>
#include <GL/glew.h>
#include <GL/glut.h>
#include "GL/freeglut.h"
#define GL_GLEXT_PROTOTYPES
#include <GL/glext.h>
#include <gl\GL.h>
#include <gl\GLU.h>
using namespace std;
```

**Comment by nigels-com** [comment]
Probably need more of the logs to make a guess.
I would recommend putting `<GL/glew.h>` first in the includes, and leaving out glext.h and GL.h.

**Comment by jawhster** [comment]
I got it working. Below are the steps that I took after starting from scratch solution file and updating main.cpp with latest.

1) added glew.h to folder C:\Program Files (x86)\Windows Kits\8.1\Include\um
2) glew.h include statement needs to come before include glut.h
3) added glew.c to project folder where main.cpp is
4) added glew.c as existing item to project
5) added wglew.h and glxew.h to folder C:\Program Files (x86)\Windows Kits\8.1\Include\um
6) modified glew.c so reference include <glew.h>, include <wglew.h>, and include <glxew.h>
