### ISSUE TITLE
#include <GL/glew.h> in glew.c

### ISSUE THREAD

**Issue by braddabug** [nigels-com/glew#95]
Problem: I'd like to be able to add glew.h and glew.c to my own code repo, but the problem is that glew.c has this line:

`#include <GL/glew.h>`

The installation instructions says to change that line in glew.c, but the problem with that is it requires me to make the change _again_ every time I upgrade to a newer version of glew. So I have a better idea...

Solution:

Change the line above to something like this:

```
#ifndef GLEW_INCLUDE
#define GLEW_INCLUDE <GL/glew.h>
#endif

#include GLEW_INCLUDE
```

Then I can just make a define to tell glew.c where to find the header, rather than having to modify the code.

The next few lines (the ones that include wglew.h and glxew.h, etc) would need something similar.

**Comment by nigels-com** [comment]
I think I'd prefer to change the instructions to recommend putting glew.h in a GL directory.

**Comment by nigels-com** [comment]
On a second thoughts, I'll go ahead and add support for this.

**Comment by nigels-com** [comment]
Here is the approach I'm considering.  We'd need the same for the other headers: glxew.h, wglew.h and eglew.h

```
#ifndef GLEW_INCLUDE
#include <GL/glew.h>
#else
#include GLEW_INCLUDE
#endif
```

**Comment by nigels-com** [comment]
This works for me:
```
$ make clean all SYSTEM=darwin CFLAGS.EXTRA="-DGLEW_INCLUDE=\<foo/glew.h\>"
```

**Comment by braddabug** [comment]
It looks like there's still a reference to GL/glew.h in glxew.h and eglew.h that's not wrapped in any kind of GLEW_INCLUDE check. Other files too, probably.

This means that if you have a local copy of glew within your project, it'll potentially try to load a different copy of glew.h than what glew.c is using.

**Comment by nigels-com** [comment]
Ah, agreed.  It was overlooked.

**Comment by nigels-com** [comment]
Looks like this is resolved.  Closing.
