### ISSUE TITLE
GLEW-2.0.0 compiled with EGL, shows only OpenGL 3.0 supported

### ISSUE THREAD

**Issue by ya-isakov** [nigels-com/glew#97]
Hello! I've compiled GLEW-2.0.0 using SYSTEM=linux-egl. When I'm checking under gnome-3.20 on wayland with mesa-12.0.1, glewinfo says that only 3.0 is supported:
> GLEW version 2.0.0
> Running on a Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)  from Intel Open Source Technology Center
> OpenGL version 3.0 Mesa 12.0.1 is supported

But at the same time, all extensions in the same glewinfo up to 4.0 are supported
[glewinfo.txt](https://github.com/nigels-com/glew/files/412053/glewinfo.txt)

**Comment by nigels-com** [comment]
I suspect that glewinfo isn't using EGL yet.  I'll take a closer look.

**Comment by nigels-com** [comment]
Try these diagnostics on your setup:

```
$ ldd lib/libGLEW.so.2.0
        linux-vdso.so.1 =>  (0x00007ffcfabcd000)
        libEGL.so.1 => /usr/lib/nvidia-361/libEGL.so.1 (0x00007f41dd3e4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f41dd01b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f41dce16000)
        libGLdispatch.so.0 => /usr/lib/nvidia-361/libGLdispatch.so.0 (0x00007f41dcb2e000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556f235e6000)

$ ldd bin/glewinfo
        linux-vdso.so.1 =>  (0x00007fff049b1000)
        libGLEW.so.2.0 => lib/libGLEW.so.2.0 (0x00007fe673452000)
        libEGL.so.1 => /usr/lib/nvidia-361/libEGL.so.1 (0x00007fe673224000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe672e5a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe672c56000)
        libGLdispatch.so.0 => /usr/lib/nvidia-361/libGLdispatch.so.0 (0x00007fe67296e000)
```

It does appear that both GLEW and glewinfo are using an EGL created context.

I think this is more a misreading of the glewinfo output which is reporting GL_VERSION_4_5 as "OK" eventhough it's just the functions that are available, not that Mesa is reporting 4.5 support.  Perhaps glewinfo ought to be reporting OK [MISSING] in the manner it does for extensions.

-- Nigel

**Comment by ya-isakov** [comment]
Yes, I've compiled GLEW with EGL, and it's definitely using it:

> yar@thinkpad ~/Downloads $ objdump -x /usr/lib/libGLEW.so.2.0 | grep EGL
>   NEEDED               libEGL.so.1
> yar@thinkpad ~/Downloads $ objdump -x /usr/bin/glewinfo | grep EGL
>   NEEDED               libEGL.so.1

The problem is that GLEW detects wrong OpenGL version in such setup, and this leads to inability to use gl33 backend to for colobot, for example.

**Comment by ya-isakov** [comment]
It seems that mesa exposes only OpenGL 3.0 under wayland EGL, so the bug is invalid for GLEW, sorry
