### ISSUE TITLE
X11: Please avoid using "Status" and "Bool" macro in glxew.h

### ISSUE THREAD

**Issue by jasjuang** [nigels-com/glew#98]
I was having trouble compiling glxew.h with OpenCV which has code something like 

``````
namespace cv {

class CV_EXPORTS_W Stitcher
{
public:
    enum Status
    {
        OK = 0,
        ......
    };
 ......
}

......
}
``````

Then I realized In line 1497 of glxew.h

``````
typedef Status ( * PFNGLXGETTRANSPARENTINDEXSUNPROC) (Display* dpy, Window overlay, Window underlay, unsigned long *pTransparentIndex);
``````
And I further track back to the header file X11/Xlib.h which is included in glxew.h has a ton of horrible macros like

``````
#define Bool int
#define Status int
#define True 1
#define False 0

// and more horrible macros
``````

Could you do a few undef in glxew.h and replace line 1497 with the below? Horrible macros should be avoided.

``````
typedef int ( * PFNGLXGETTRANSPARENTINDEXSUNPROC) (Display* dpy, Window overlay, Window underlay, unsigned long *pTransparentIndex);
``````

**Comment by nigels-com** [comment]
Is it possible for OpenCV to narrow or eliminate including 'glxew.h'.  The X11 API is certainly crufty and problematic, but I don't think hacking at glxew.h is the best solution.

**Comment by nigels-com** [comment]
The conundrum for GLEW is that there is likely to be end-user code depending on these macros via 'glxew.h'.  For that reason I'd be reluctant to change it.

**Comment by jasjuang** [comment]
It is my graphics application that needs to include both glxew.h and OpenCV. It would be hard to ask OpenCV to rename their enum when the fault is obviously from X11. Now my temporary solution is adding a "undef Status" right after I include glxew.h but it doesn't feel like the best way to resolve this.

I would argue that if the end-user code is going to use those horrible macros they would've included Xlib.h directly themselves instead of going through glxew.h indirectly. I say it will be beneficial to change it.

**Comment by nigels-com** [comment]
Horrible or not, these macros are entrenched.  Be pragmatic and #undef the offending macros after including glxew.h.  But be aware that other X11-dependent headers may require these.  Ideally OpenCV would adjust their naming to avoid colliding with X11 macros.

**Comment by jasjuang** [comment]
Ok let me file an issue on OpenCV and see if they are willing to budge.

**Comment by nigels-com** [comment]
It appears that the OpenCV folks intend to resolve this:
https://github.com/opencv/opencv/issues/7113

**Comment by jasjuang** [comment]
Yes, but for some reason they haven't merge the pull request yet.

**Comment by nigels-com** [comment]
Worth a friendly reminder.  Especially if you can report positively that it fixes your problem and all the tests pass.

**Comment by jasjuang** [comment]
I just leave a comment to inquire about the status, hopefully the fix will kick in soon

**Comment by jasjuang** [comment]
OpenCV fixed this.
